/**
 * Writes a RUNNING minimal browser game into <project>/build/ that loads the
 * approved assets. The chat agent then edits build/game.js with normal file
 * tools to write the real game. assets.js/mp.js are regenerated on every
 * scaffold call; game.js/index.html are only written when missing unless
 * overwrite:true (so the agent's code is never clobbered).
 */
import fs from 'fs';
import path from 'path';
import { advanceStage, fromRel, gameDir, loadGame, mutateGame, type GameProject } from './project.js';

export const THREE_CDN = 'https://unpkg.com/three@0.160.0/build/three.module.js';

function manifest(ws: string, p: GameProject, buildDir: string) {
  const images: Record<string, string> = {};
  const audio: Record<string, string> = {};
  const copied: string[] = [];
  for (const a of p.assets) {
    if (a.status !== 'approved' || !a.path) continue;
    let src: string;
    try { src = fromRel(ws, a.path); } catch { continue; }
    if (!fs.existsSync(src)) continue;
    const isAudio = a.kind === 'sfx' || a.kind === 'music';
    const sub = isAudio ? 'audio' : 'assets';
    const name = `${a.name}${path.extname(src)}`;
    fs.mkdirSync(path.join(buildDir, sub), { recursive: true });
    fs.copyFileSync(src, path.join(buildDir, sub, name));
    (isAudio ? audio : images)[a.name] = `${sub}/${name}`;
    copied.push(`${sub}/${name}`);
  }
  return { images, audio, copied };
}

function assetsJs(images: Record<string, string>, audio: Record<string, string>): string {
  return `// Generated by Prometheus game_project scaffold. Regenerated on each scaffold call; do not hand-edit.
export const MANIFEST = ${JSON.stringify({ images, audio }, null, 2)};

/** Preload every image + audio file. Resolves { images: {name: HTMLImageElement}, audio: {name: HTMLAudioElement} }. */
export async function loadAssets(onProgress) {
  const entries = [...Object.entries(MANIFEST.images).map(([k, v]) => ['img', k, v]), ...Object.entries(MANIFEST.audio).map(([k, v]) => ['aud', k, v])];
  const out = { images: {}, audio: {} };
  let done = 0;
  await Promise.all(entries.map(([t, k, src]) => new Promise((resolve) => {
    const finish = () => { done++; if (onProgress) onProgress(done / Math.max(1, entries.length)); resolve(); };
    if (t === 'img') { const im = new Image(); im.onload = finish; im.onerror = finish; im.src = src; out.images[k] = im; }
    else { const a = new Audio(); a.preload = 'auto'; a.oncanplaythrough = finish; a.onerror = finish; a.src = src; out.audio[k] = a; setTimeout(finish, 3000); }
  })));
  return out;
}

/** Play a sound (clones so overlapping plays work). */
export function play(assets, name, volume = 0.6) {
  const a = assets && assets.audio && assets.audio[name];
  if (!a) return;
  try { const c = a.cloneNode(); c.volume = volume; c.play().catch(() => {}); } catch {}
}
`;
}

function mpJs(): string {
  return `// Multiplayer client for the Prometheus game room relay (SSE + POST).
// MP.connect(room) -> Promise<playerId>; MP.send(state); MP.on('state'|'join'|'leave'|'welcome', fn)
const handlers = {};
let base = '', playerId = '', es = null;
function emit(t, d) { (handlers[t] || []).forEach((fn) => { try { fn(d); } catch (e) { console.error(e); } }); }
function apiRoot() {
  const u = new URL(location.href);
  const i = u.pathname.indexOf('/api/game-projects/');
  return i >= 0 ? u.origin : (window.PROM_GATEWAY || u.origin);
}
export const MP = {
  get id() { return playerId; },
  on(type, fn) { (handlers[type] = handlers[type] || []).push(fn); return MP; },
  connect(room) {
    base = apiRoot() + '/api/game-rooms/' + encodeURIComponent(room || 'lobby');
    return new Promise((resolve, reject) => {
      es = new EventSource(base + '/events');
      es.onmessage = (ev) => {
        let m; try { m = JSON.parse(ev.data); } catch { return; }
        if (m.type === 'welcome') { playerId = m.playerId; emit('welcome', m); resolve(playerId); }
        else emit(m.type, m);
      };
      es.onerror = () => { if (!playerId) reject(new Error('room connect failed')); };
    });
  },
  send(state) {
    if (!playerId) return;
    fetch(base + '/send', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ playerId, type: 'state', data: state }) }).catch(() => {});
  },
  close() { if (es) es.close(); es = null; playerId = ''; },
};
window.MP = MP;
`;
}

function indexHtml(p: GameProject): string {
  const three = p.design.engine === 'three';
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
<title>${p.title.replace(/[<>&]/g, '')}</title>
<style>
html,body{margin:0;height:100%;background:#0b0b10;color:#eee;font-family:system-ui,sans-serif;overflow:hidden;touch-action:none}
#game{display:block;width:100vw;height:100vh}
#hud{position:fixed;left:12px;top:10px;font-size:14px;pointer-events:none;text-shadow:0 1px 2px #000}
#loading{position:fixed;inset:0;display:flex;align-items:center;justify-content:center;font-size:16px}
</style>
${three ? `<script type="importmap">{"imports":{"three":"${THREE_CDN}"}}</script>\n` : ''}</head>
<body>
<canvas id="game"></canvas>
<div id="hud"></div>
<div id="loading">Loading…</div>
<script type="module" src="./game.js"></script>
</body>
</html>
`;
}

function canvasGameJs(p: GameProject): string {
  return `// ${p.title} — ${p.design.genre} / ${p.design.style}. Starter scaffold: REPLACE with the real game.
import { loadAssets, play } from './assets.js';
${p.design.multiplayer ? "import { MP } from './mp.js';\n" : ''}
const canvas = document.getElementById('game');
const ctx = canvas.getContext('2d');
const hud = document.getElementById('hud');
const W = 960, H = 540;
function fit() { const s = Math.min(innerWidth / W, innerHeight / H); canvas.width = W; canvas.height = H; canvas.style.width = (W * s) + 'px'; canvas.style.height = (H * s) + 'px'; canvas.style.margin = ((innerHeight - H * s) / 2) + 'px auto 0'; }
addEventListener('resize', fit); fit();
ctx.imageSmoothingEnabled = ${p.design.style === 'pixel' ? 'false' : 'true'};

const keys = new Set();
addEventListener('keydown', (e) => { keys.add(e.key.toLowerCase()); if (e.key === ' ') { play(assets, 'jump'); } });
addEventListener('keyup', (e) => keys.delete(e.key.toLowerCase()));
let touch = null;
canvas.addEventListener('pointerdown', (e) => { touch = { x: e.clientX, y: e.clientY }; play(assets, 'click'); });
canvas.addEventListener('pointermove', (e) => { if (touch) touch = { x: e.clientX, y: e.clientY }; });
addEventListener('pointerup', () => { touch = null; });

const player = { x: W / 2, y: H / 2, w: 64, h: 64, speed: 260 };
const others = new Map();
let assets = { images: {}, audio: {} };

function update(dt) {
  let dx = (keys.has('arrowright') || keys.has('d') ? 1 : 0) - (keys.has('arrowleft') || keys.has('a') ? 1 : 0);
  let dy = (keys.has('arrowdown') || keys.has('s') ? 1 : 0) - (keys.has('arrowup') || keys.has('w') ? 1 : 0);
  if (touch) { const r = canvas.getBoundingClientRect(); const tx = (touch.x - r.left) * W / r.width, ty = (touch.y - r.top) * H / r.height; dx = Math.sign(tx - player.x) * (Math.abs(tx - player.x) > 4 ? 1 : 0); dy = Math.sign(ty - player.y) * (Math.abs(ty - player.y) > 4 ? 1 : 0); }
  player.x = Math.max(player.w / 2, Math.min(W - player.w / 2, player.x + dx * player.speed * dt));
  player.y = Math.max(player.h / 2, Math.min(H - player.h / 2, player.y + dy * player.speed * dt));
}

function drawSprite(name, x, y, w, h, fallback) {
  const im = assets.images[name];
  if (im && im.complete && im.naturalWidth) ctx.drawImage(im, x - w / 2, y - h / 2, w, h);
  else { ctx.fillStyle = fallback; ctx.fillRect(x - w / 2, y - h / 2, w, h); }
}

function draw() {
  const bg = assets.images.background || Object.values(assets.images).find((i) => i.naturalWidth >= 512);
  if (bg && bg.naturalWidth) ctx.drawImage(bg, 0, 0, W, H); else { ctx.fillStyle = '#1b1b2b'; ctx.fillRect(0, 0, W, H); }
  for (const o of others.values()) drawSprite('player', o.x, o.y, player.w, player.h, '#4af');
  const heroName = assets.images.player ? 'player' : Object.keys(assets.images).find((k) => k !== 'background');
  drawSprite(heroName, player.x, player.y, player.w, player.h, '#fc3');
  hud.textContent = '${p.title.replace(/'/g, "\\'")} — arrows/WASD or touch to move, space to jump';
}

let last = performance.now();
function loop(now) {
  const dt = Math.min(0.05, (now - last) / 1000); last = now;
  update(dt); draw();
${p.design.multiplayer ? '  if (MP.id && Math.round(now / 50) % 2 === 0) MP.send({ x: player.x, y: player.y });\n' : ''}  requestAnimationFrame(loop);
}

assets = await loadAssets();
document.getElementById('loading').remove();
${p.design.multiplayer ? `MP.on('state', (m) => others.set(m.from, m.data)).on('leave', (m) => others.delete(m.playerId));
MP.connect(new URLSearchParams(location.search).get('room') || '${p.id}').catch((e) => console.warn(e));
` : ''}window.__game = { player, assets };
requestAnimationFrame(loop);
`;
}

function threeGameJs(p: GameProject): string {
  return `// ${p.title} — ${p.design.genre} / ${p.design.style} (Three.js). Starter scaffold: REPLACE with the real game.
import * as THREE from 'three';
import { loadAssets, play, MANIFEST } from './assets.js';
${p.design.multiplayer ? "import { MP } from './mp.js';\n" : ''}
const canvas = document.getElementById('game');
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });
renderer.setPixelRatio(Math.min(2, devicePixelRatio));
const scene = new THREE.Scene();
scene.background = new THREE.Color(0x10131c);
const camera = new THREE.PerspectiveCamera(60, 1, 0.1, 500);
camera.position.set(0, 6, 10); camera.lookAt(0, 0, 0);
scene.add(new THREE.HemisphereLight(0xffffff, 0x334455, 1.1));
const sun = new THREE.DirectionalLight(0xffffff, 1.2); sun.position.set(5, 10, 4); scene.add(sun);
function fit() { renderer.setSize(innerWidth, innerHeight); camera.aspect = innerWidth / innerHeight; camera.updateProjectionMatrix(); }
addEventListener('resize', fit); fit();

const assets = await loadAssets();
document.getElementById('loading').remove();
const loader = new THREE.TextureLoader();
const texName = Object.keys(MANIFEST.images).find((k) => /tile|track|texture|ground/.test(k)) || Object.keys(MANIFEST.images)[0];
const groundMat = new THREE.MeshStandardMaterial({ color: 0x556070 });
if (texName) loader.load(MANIFEST.images[texName], (t) => { t.wrapS = t.wrapT = THREE.RepeatWrapping; t.repeat.set(8, 8); t.colorSpace = THREE.SRGBColorSpace; groundMat.map = t; groundMat.color.set(0xffffff); groundMat.needsUpdate = true; });
const ground = new THREE.Mesh(new THREE.PlaneGeometry(60, 60), groundMat); ground.rotation.x = -Math.PI / 2; scene.add(ground);
const player = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshStandardMaterial({ color: 0xffcc33 }));
player.position.y = 0.5; scene.add(player);
const others = new Map();

const keys = new Set();
addEventListener('keydown', (e) => { keys.add(e.key.toLowerCase()); if (e.key === ' ') play(assets, 'jump'); });
addEventListener('keyup', (e) => keys.delete(e.key.toLowerCase()));
let touch = null;
canvas.addEventListener('pointerdown', (e) => { touch = e; play(assets, 'click'); });
canvas.addEventListener('pointermove', (e) => { if (touch) touch = e; });
addEventListener('pointerup', () => { touch = null; });

let last = performance.now();
function loop(now) {
  const dt = Math.min(0.05, (now - last) / 1000); last = now;
  let dx = (keys.has('arrowright') || keys.has('d') ? 1 : 0) - (keys.has('arrowleft') || keys.has('a') ? 1 : 0);
  let dz = (keys.has('arrowdown') || keys.has('s') ? 1 : 0) - (keys.has('arrowup') || keys.has('w') ? 1 : 0);
  if (touch) { dx = Math.sign(touch.clientX - innerWidth / 2); dz = Math.sign(touch.clientY - innerHeight / 2); }
  player.position.x += dx * 6 * dt; player.position.z += dz * 6 * dt;
  player.rotation.y += dt;
  camera.position.set(player.position.x, 6, player.position.z + 10); camera.lookAt(player.position);
${p.design.multiplayer ? `  if (MP.id) MP.send({ x: player.position.x, z: player.position.z });
  for (const [id, o] of others) { if (!o.mesh) { o.mesh = new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshStandardMaterial({ color: 0x44aaff })); scene.add(o.mesh); } o.mesh.position.set(o.x, 0.5, o.z); }
` : ''}  renderer.render(scene, camera);
  document.getElementById('hud').textContent = '${p.title.replace(/'/g, "\\'")} — arrows/WASD or touch';
  requestAnimationFrame(loop);
}
${p.design.multiplayer ? `MP.on('state', (m) => { const o = others.get(m.from) || {}; Object.assign(o, m.data); others.set(m.from, o); })
  .on('leave', (m) => { const o = others.get(m.playerId); if (o && o.mesh) scene.remove(o.mesh); others.delete(m.playerId); });
MP.connect(new URLSearchParams(location.search).get('room') || '${p.id}').catch((e) => console.warn(e));
` : ''}window.__game = { scene, player, assets };
requestAnimationFrame(loop);
`;
}

export async function writeScaffold(ws: string, projectId: string, args: { overwrite?: boolean } = {}): Promise<{ buildDir: string; files: string[]; copied: string[]; gameJs: string; kept: string[] }> {
  const p = loadGame(ws, projectId);
  const buildDir = path.join(gameDir(ws, projectId), 'build');
  fs.mkdirSync(buildDir, { recursive: true });
  const { images, audio, copied } = manifest(ws, p, buildDir);
  const files: string[] = [];
  const kept: string[] = [];
  const write = (name: string, content: string, always = false) => {
    const f = path.join(buildDir, name);
    if (!always && !args.overwrite && fs.existsSync(f)) { kept.push(name); return; }
    fs.writeFileSync(f, content);
    files.push(name);
  };
  write('assets.js', assetsJs(images, audio), true);
  if (p.design.multiplayer) write('mp.js', mpJs(), true);
  write('index.html', indexHtml(p));
  write('game.js', p.design.engine === 'three' ? threeGameJs(p) : canvasGameJs(p));
  await mutateGame(ws, projectId, (proj) => { advanceStage(proj, 'playable'); });
  const rel = path.relative(ws, path.join(buildDir, 'game.js')).split(path.sep).join('/');
  return { buildDir: path.relative(ws, buildDir).split(path.sep).join('/'), files, copied, gameJs: rel, kept };
}
