// GENERATED by scripts/gen-prom-viz-reference.mjs from web-ui/vendor/prom-viz/prom-viz.js HELP. Do not edit.
export const PROM_VIZ_SIGNATURES: readonly string[] = [
  "ui.page({title, subtitle, kicker, source})",
  "ui.kpis(t, [{label, value, format, delta, good:'up'|'down', deltaFormat, note, spark:[n], color}])",
  "s = ui.section(t, {title, subtitle, kicker, right, card})",
  "g = ui.grid(t, columns)",
  "c = ui.card(t)",
  "ui.callout(t, html)",
  "ui.badge(text, 'ok'|'warn'|'bad'|'accent') -> html string",
  "ui.chart(t, {type:'line'|'area'|'stacked'|'bar'|'stackedBar', x:[labels], series:[{name, values:[n], color}], format, xFormat, min, max, annotations:[{x, label}], target:{value, label}, band, legend, height, ask, onClick})",
  "ui.bars(t, {items:[{label, value, color, note}], format, highlight:'max'|label, sort, limit, valueLabel, ask, onClick})",
  "ui.donut(t, {items:[{label, value}], format, center:{value, label}})",
  "ui.heatmap(t, {rows:[labels], cols:[labels], values:[[n]] (rows x cols), format, min, max, diverging, mark, colLabelEvery, legendLabel, ask, onClick})",
  "ui.treemap(t, {data:{name, children:[{name, value} | {name, children}]} | items:[{name, value}], format, height, ask, onClick})",
  "ui.table(t, {columns:[{key, label, format, render:(v,row)=>html}], rows:[{key:value}], sort, limit, ask, onRowClick})",
  "ui.tabs(t, {tabs:[{label, render:(panel)=>void} | {label, html}], active, key})",
  "ui.segmented(t, {options:[string|{label,value}], value, onChange(v), key, fireInitial})",
  "ui.compare(t, {variants:[{name, html, css, render(stage), note}], pickPrompt, key})",
  "ui.timeline(t, {items:[{lane, label, start, end, status:'ok'|'bad'|'warn'|'run', color, note}], format:'time'|'date'|'num', markers:[{at, label}], now, colorBy, title, ask, onClick}) start/end = Date | ISO | number",
  "ui.sankey(t, {links:[{source, target, value}], format, height, valueLabel, title, ask, onClick})",
  "ui.slider(t, {label, min, max, step, value, format, note, key, onChange(v)}) -> {el, get, set}",
  "ui.params(t, {params:[{key, label, min, max, step, value, format, note}], onChange(values), card}) -> {values, el, set}",
  "ui.loop(t, {step(dt, t, frame), autoplay, speed, speeds, controls:true, label, reset()}) -> {play, pause, reset, running}",
  "ui.form(t, {title, subtitle, fields:[{key, label, type:'text'|'number'|'textarea'|'select'|'toggle'|'chips'|'slider', options, value, min, max, step, multiple, placeholder, required}], submit, prompt:'Template {key}' | fn(values), send, key, onSubmit(values)}) -> {el, values()}",
  "ui.exportBar(t, {png:true, x:true, csv:rows|fn, columns, name})",
  "ui.legend(t, series:[{name}], colors:[css], onToggle(hiddenMap))",
  "ui.data(id='data') -> parsed JSON from <script type=\"application/json\" id=\"data\"> or window.PROM_DATA",
  "ui.fmt(v, 'int'|'num'|'compact'|'usd'|'usd0'|'usd2'|'pct'|'pct1'|'pctRaw'|'delta'|'ms'|'dur'|'bytes'|'{v} units'|fn) -> string. Every format option accepts these.",
  "ui.state.get(key, fallback) / ui.state.set(key, value) - persisted widget state",
  "ui.ask(prompt, title) - drop a follow-up into the chat composer. Views also take ask:'Why is {label} {value}?'",
  "ui.help(name?) -> {sig, ex} for one view, or the full map"
];

export const PROM_VIZ_REFERENCE =
  'Viz Kit exact call shapes (t = target element or null for the page root; never pass bare arrays except to ui.kpis; ui.help(name) returns {sig, ex} at runtime): ' +
  PROM_VIZ_SIGNATURES.join('; ') + '.';
