
(() => {
  'use strict';
  const canvas=document.getElementById('game'), ctx=canvas.getContext('2d',{alpha:false});
  const $=id=>document.getElementById(id);
  const hud={health:$('healthPill'),points:$('pointsPill'),wave:$('wavePill'),pause:$('pausePill'),weapon:$('weaponPill'),ammo:$('ammoPill'),zombies:$('zombiePill'),perks:$('perkRow'),prompt:$('prompt'),center:$('centerMessage'),start:$('startButton'),nub:$('nub'),hitFlash:$('hitFlash'),powerFlash:$('powerFlash')};
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), dist=(a,b,c,d)=>Math.hypot(a-c,b-d), angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b)), rand=(a,b)=>a+Math.random()*(b-a);
  const MAP=['########################','#....g.......#.....p...#','#............#.........#','#..s..##..D..#..w......#','#......#.....#.........#','#..w...#.....D.....S...#','#......#.....#.........#','###D####.....####D######','#......#.....#.........#','#..j...D.....D...r.....#','#......#.....#.........#','#..S...#.....#.....S...#','#......#.....#.........#','#....p.#.....#..m......#','########################'];
  const H=MAP.length,W=MAP[0].length, baseMap=MAP.map(r=>[...r].map(ch=>ch==='#'?1:0));
  const weapons={pistol:{id:'pistol',name:'M1911',price:0,dmg:55,fireMs:235,mag:10,reserve:90,reloadMs:850,spread:.018,range:13,cell:4,color:'#ffe8a3'},smg:{id:'smg',name:'WALL SMG',price:950,dmg:23,fireMs:92,mag:32,reserve:160,reloadMs:1120,spread:.045,range:10.5,cell:5,color:'#95d9ff'},shotgun:{id:'shotgun',name:'TRENCH SHOTGUN',price:1250,dmg:25,pellets:8,fireMs:700,mag:6,reserve:48,reloadMs:1320,spread:.145,range:6.5,cell:6,color:'#ffca86'},rifle:{id:'rifle',name:'BATTLE RIFLE',price:1600,dmg:63,fireMs:205,mag:20,reserve:120,reloadMs:1220,spread:.021,range:14.5,cell:7,color:'#c6ff9d'}};
  const perkDefs={jug:{id:'jug',name:'JUG',price:1800,desc:'+75 health',color:'#ff6565',cell:8},speed:{id:'speed',name:'SPEED',price:1400,desc:'fast reload',color:'#74c7ff',cell:9},double:{id:'double',name:'DOUBLE',price:2000,desc:'+35% damage',color:'#ffcf4a',cell:10},stamin:{id:'stamin',name:'STAMIN',price:1200,desc:'fast move',color:'#63ff9f',cell:11}};
  const wallGuns=[{x:3.5,y:3.5,weapon:'smg'},{x:3.5,y:5.5,weapon:'shotgun'},{x:16.5,y:5.5,weapon:'rifle'}], perkMachines=[{x:4.5,y:9.5,perk:'jug'},{x:18.5,y:9.5,perk:'speed'},{x:5.5,y:13.5,perk:'double'},{x:18.5,y:1.5,perk:'stamin'}], doors=[{id:'d1',x:3,y:7,price:750,open:false},{id:'d2',x:10,y:3,price:1000,open:false},{id:'d3',x:13,y:5,price:1250,open:false},{id:'d4',x:15,y:7,price:1500,open:false},{id:'d5',x:7,y:9,price:1000,open:false},{id:'d6',x:13,y:9,price:1250,open:false}];
  const startSpawns=[{x:8.5,y:2.5},{x:9.5,y:1.5},{x:6.5,y:5.5},{x:1.5,y:6.5},{x:5.5,y:1.5}], allSpawns=[...startSpawns,{x:18.5,y:2.5},{x:2.5,y:12.5},{x:20.5,y:12.5},{x:10.5,y:13.5}];
  const sheet=new Image(); sheet.src='assets/pocket-zombies-sprites.png'; let sheetReady=false; sheet.onload=()=>{sheetReady=true};
  const cut={z0:[0,0,256,256],z1:[256,0,256,256],z2:[512,0,256,256],z3:[768,0,256,256],pistol:[0,256,256,256],smg:[256,256,256,256],shotgun:[512,256,256,256],rifle:[768,256,256,256],jug:[0,512,256,256],speed:[256,512,256,256],double:[512,512,256,256],stamin:[768,512,256,256],max:[0,768,256,256],insta:[256,768,256,256],points:[512,768,256,256],nuke:[768,768,256,256]};
  const state={running:false,paused:false,gameOver:false,last:0,shake:0,player:{x:2.5,y:2.5,a:0,hp:125,maxHp:125,points:1200,kills:0,speed:2.75,alive:true},wave:1,waveState:'ready',waveTimer:0,zombiesToSpawn:0,spawnCooldown:0,zombies:[],floaters:[],powerups:[],particles:[],owned:['pistol'],current:'pistol',ammo:{pistol:{mag:10,reserve:90},smg:{mag:0,reserve:0},shotgun:{mag:0,reserve:0},rifle:{mag:0,reserve:0}},perks:new Set(),activePowers:{insta:0,double:0},reloading:false,reloadTimer:0,lastShot:0,lastHurt:0,prompt:null,audio:null,audioReady:false};
  const keys=new Set(), touch={moveId:null,lookId:null,moveStart:null,move:{x:0,y:0},lookLast:null,firing:false};
  const tex={}; function makeTex(name,w,h,draw){const c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d');draw(g,w,h);tex[name]=c}
  function makeAssets(){makeTex('wall',96,96,(g,w,h)=>{g.fillStyle='#2e251d';g.fillRect(0,0,w,h);for(let y=0;y<h;y+=24)for(let x=(y/24%2)*-24;x<w;x+=48){g.fillStyle=(x+y)%96?'#49392d':'#392c23';g.fillRect(x+1,y+1,46,22);g.strokeStyle='rgba(0,0,0,.45)';g.strokeRect(x+1,y+1,46,22)}g.fillStyle='rgba(94,255,106,.08)';for(let i=0;i<10;i++)g.fillRect(rand(0,w),rand(0,h),rand(2,8),rand(10,28))});makeTex('door',96,96,(g,w,h)=>{g.fillStyle='#18120e';g.fillRect(0,0,w,h);g.fillStyle='#5a3f25';g.fillRect(14,0,68,h);g.fillStyle='#25180e';for(let y=8;y<h;y+=16)g.fillRect(18,y,60,4);g.fillStyle='#ffcf4a';g.fillRect(68,42,8,8)});makeTex('floor',160,160,(g,w,h)=>{g.fillStyle='#14100d';g.fillRect(0,0,w,h);for(let i=0;i<240;i++){g.fillStyle=`rgba(${55+Math.random()*60},${45+Math.random()*35},${35+Math.random()*25},.22)`;g.fillRect(rand(0,w),rand(0,h),rand(1,4),rand(1,4))}})}
  function spriteCell(index){return {sx:(index%4)*256,sy:Math.floor(index/4)*256,sw:256,sh:256}}
  function drawSpriteCell(g,index,x,y,w,h,alpha=1){
    if(sheetReady){
      const c=spriteCell(index); const pad=index<4?34:18;
      g.save(); g.globalAlpha=alpha;
      g.drawImage(sheet,c.sx+pad,c.sy+pad,c.sw-pad*2,c.sh-pad*2,x,y,w,h);
      g.restore();
    } else { g.fillStyle='rgba(90,160,80,.9)'; g.fillRect(x+w*.25,y+h*.15,w*.5,h*.8); }
  }
  function resize(){const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.floor(innerWidth*d);canvas.height=Math.floor(innerHeight*d);ctx.setTransform(d,0,0,d,0,0)} addEventListener('resize',resize,{passive:true}); resize(); makeAssets();
  function isDoorClosed(x,y){return doors.some(d=>!d.open&&Math.floor(x)===d.x&&Math.floor(y)===d.y)} function isWall(x,y){const ix=Math.floor(x),iy=Math.floor(y);return ix<0||iy<0||ix>=W||iy>=H||baseMap[iy][ix]===1||isDoorClosed(ix,iy)}
  function castRay(px,py,a){let sin=Math.sin(a),cos=Math.cos(a),d=0,lastX=px,lastY=py;while(d<22){d+=.035;const x=px+cos*d,y=py+sin*d;if(isWall(x,y)){return {d,x,y,type:isDoorClosed(x,y)?2:1,frac:Math.abs((Math.abs(x-lastX)>Math.abs(y-lastY)?y:x)%1)}}lastX=x;lastY=y}return {d:22,x:px+cos*22,y:py+sin*22,type:0,frac:0}}
  function hasLine(x1,y1,x2,y2){const steps=Math.ceil(dist(x1,y1,x2,y2)*12);for(let i=1;i<steps;i++){const t=i/steps;if(isWall(x1+(x2-x1)*t,y1+(y2-y1)*t))return false}return true}
  function startGame(){unlockAudio();hud.center.style.display='none';state.running=true;state.paused=false;state.gameOver=false;Object.assign(state.player,{x:2.5,y:2.5,a:0,hp:125,maxHp:125,points:1200,kills:0,speed:2.75,alive:true});state.wave=0;state.zombies=[];state.powerups=[];state.floaters=[];state.perks=new Set();state.owned=['pistol'];state.current='pistol';state.ammo={pistol:{mag:10,reserve:90},smg:{mag:0,reserve:0},shotgun:{mag:0,reserve:0},rifle:{mag:0,reserve:0}};for(const d of doors)d.open=false;nextWave();updateHud()}
  function nextWave(){state.wave++;state.waveState='spawning';state.waveTimer=0;state.zombiesToSpawn=5+Math.floor(state.wave*2.25);state.spawnCooldown=.55;state.player.points+=150;floater('WAVE '+state.wave,state.player.x,state.player.y,'#ffcf4a')}
  function spawnZombie(){const list=state.wave<3?startSpawns:allSpawns;const s=list[Math.floor(Math.random()*list.length)];const tier=Math.random()<Math.min(.08+state.wave*.025,.32)?(Math.random()<.55?'brute':'crawler'):'normal';const hp=(tier==='brute'?150:tier==='crawler'?58:92)+state.wave*15;state.zombies.push({x:s.x,y:s.y,tier,cell:tier==='brute'?2:tier==='crawler'?1:Math.random()<.2?3:0,hp,maxHp:hp,speed:(tier==='brute'?1.0:tier==='crawler'?1.65:1.32)+state.wave*.035,attack:.25,hurt:0,dead:false,anim:Math.random()*9})}
  function fire(){if(!state.running||state.gameOver||state.reloading)return;unlockAudio();const now=performance.now(),w=weapons[state.current],ammo=state.ammo[state.current],rate=w.fireMs/(state.perks.has('double')?1.12:1);if(now-state.lastShot<rate)return;if(ammo.mag<=0){reload();beep(120,.05,'sawtooth',.03);return}state.lastShot=now;ammo.mag--;state.shake=.075;beep(state.current==='shotgun'?82:170,.045,'square',.035);for(let i=0;i<(w.pellets||1);i++)shootRay(state.player.a+rand(-w.spread,w.spread),w);for(const z of state.zombies)if(!z.dead&&dist(z.x,z.y,state.player.x,state.player.y)<.95){const a=Math.atan2(z.y-state.player.y,z.x-state.player.x);if(!isWall(z.x+Math.cos(a)*.18,z.y))z.x+=Math.cos(a)*.18;if(!isWall(z.x,z.y+Math.sin(a)*.18))z.y+=Math.sin(a)*.18}if(ammo.mag<=0)setTimeout(reload,80);updateHud()}
  function shootRay(a,w){const p=state.player;let best=null,bestT=w.range;for(const z of state.zombies){if(z.dead)continue;const dx=z.x-p.x,dy=z.y-p.y,d=Math.hypot(dx,dy);if(d>bestT)continue;const ad=Math.abs(angleDiff(Math.atan2(dy,dx),a)),radius=z.tier==='brute'?.56:.43;if(ad<Math.atan2(radius,d)&&hasLine(p.x,p.y,z.x,z.y)){best=z;bestT=d}}if(best)damageZombie(best,w.dmg*(state.activePowers.insta>0?99:1)*(state.perks.has('double')?1.35:1))}
  function damageZombie(z,dmg){z.hp-=dmg;z.hurt=.12;state.player.points+=state.activePowers.double>0?20:10;floater('+'+(state.activePowers.double>0?20:10),z.x,z.y,'#ffcf4a');if(z.hp<=0&&!z.dead){z.dead=true;state.player.kills++;state.player.points+=state.activePowers.double>0?120:60;floater('KILL',z.x,z.y,'#63ff9f');maybeDrop(z.x,z.y);beep(52,.08,'sawtooth',.04)}}
  function reload(){if(!state.running||state.reloading)return;const w=weapons[state.current],ammo=state.ammo[state.current];if(ammo.mag>=w.mag||ammo.reserve<=0)return;state.reloading=true;state.reloadTimer=(w.reloadMs/1000)*(state.perks.has('speed')?.55:1);updateHud()} function finishReload(){const w=weapons[state.current],ammo=state.ammo[state.current],take=Math.min(w.mag-ammo.mag,ammo.reserve);ammo.mag+=take;ammo.reserve-=take;state.reloading=false;updateHud()}
  function maybeDrop(x,y){if(Math.random()>.22)return;const type=['max','insta','double','nuke'][Math.floor(Math.random()*4)];state.powerups.push({x,y,type,t:14,bob:0})} function pickupPower(pu){hud.powerFlash.style.opacity=.85;setTimeout(()=>hud.powerFlash.style.opacity=0,140);if(pu.type==='max'){for(const id of state.owned)state.ammo[id].reserve=Math.max(state.ammo[id].reserve,weapons[id].reserve);floater('MAX AMMO',state.player.x,state.player.y,'#74c7ff')}if(pu.type==='insta'){state.activePowers.insta=18;floater('INSTA-KILL',state.player.x,state.player.y,'#fff')}if(pu.type==='double'){state.activePowers.double=22;floater('DOUBLE POINTS',state.player.x,state.player.y,'#ffcf4a')}if(pu.type==='nuke'){for(const z of state.zombies)if(!z.dead)damageZombie(z,9999);floater('NUKE',state.player.x,state.player.y,'#ff884d')}beep(520,.12,'triangle',.06);updateHud()}
  function interact(){if(!state.running||state.gameOver)return;const item=findInteractable();if(!item)return;const p=state.player;if(item.kind==='door'){if(p.points>=item.obj.price){p.points-=item.obj.price;item.obj.open=true;floater('DOOR OPEN',p.x,p.y,'#ffcf4a');beep(260,.12,'square',.05)}else deny()}if(item.kind==='gun'){const w=weapons[item.obj.weapon];if(p.points>=w.price){p.points-=w.price;if(!state.owned.includes(w.id))state.owned.push(w.id);state.current=w.id;state.ammo[w.id]={mag:w.mag,reserve:w.reserve};floater(w.name,p.x,p.y,w.color);beep(330,.10,'triangle',.05)}else deny()}if(item.kind==='perk'){const perk=perkDefs[item.obj.perk];if(!state.perks.has(perk.id)){if(p.points>=perk.price){p.points-=perk.price;state.perks.add(perk.id);if(perk.id==='jug'){p.maxHp=175;p.hp=Math.min(p.maxHp,p.hp+75)}if(perk.id==='stamin')p.speed=3.15;floater(perk.name,p.x,p.y,perk.color);beep(430,.12,'triangle',.05)}else deny()}}updateHud()} function deny(){floater('NEED POINTS',state.player.x,state.player.y,'#ff7070');beep(90,.08,'sawtooth',.035)}
  function findInteractable(){const p=state.player,c=[];for(const d of doors)if(!d.open&&dist(p.x,p.y,d.x+.5,d.y+.5)<1.35)c.push({kind:'door',obj:d,d:dist(p.x,p.y,d.x+.5,d.y+.5),label:`Open door $${d.price}`});for(const g of wallGuns){const w=weapons[g.weapon];if(dist(p.x,p.y,g.x,g.y)<1.45)c.push({kind:'gun',obj:g,d:dist(p.x,p.y,g.x,g.y),label:`Buy ${w.name} $${w.price}`})}for(const pm of perkMachines){const perk=perkDefs[pm.perk];if(dist(p.x,p.y,pm.x,pm.y)<1.45)c.push({kind:'perk',obj:pm,d:dist(p.x,p.y,pm.x,pm.y),label:state.perks.has(perk.id)?`${perk.name} owned`:`Buy ${perk.name} $${perk.price} - ${perk.desc}`})}return c.sort((a,b)=>a.d-b.d)[0]||null}
  function update(dt){if(!state.running||state.gameOver||state.paused)return;const p=state.player;state.shake=Math.max(0,state.shake-dt);state.activePowers.insta=Math.max(0,state.activePowers.insta-dt);state.activePowers.double=Math.max(0,state.activePowers.double-dt);let mx=touch.move.x,my=touch.move.y;if(keys.has('KeyW')||keys.has('ArrowUp'))my-=1;if(keys.has('KeyS')||keys.has('ArrowDown'))my+=1;if(keys.has('KeyA')||keys.has('ArrowLeft'))mx-=1;if(keys.has('KeyD')||keys.has('ArrowRight'))mx+=1;if(keys.has('KeyQ'))p.a-=dt*2.4;if(keys.has('KeyE'))p.a+=dt*2.4;const m=Math.hypot(mx,my);if(m>.05){mx/=Math.max(1,m);my/=Math.max(1,m);const sp=p.speed*dt,ca=Math.cos(p.a),sa=Math.sin(p.a);tryMove((ca*my+Math.cos(p.a+Math.PI/2)*mx)*sp,(sa*my+Math.sin(p.a+Math.PI/2)*mx)*sp)}if(touch.firing)fire();if(state.reloading){state.reloadTimer-=dt;if(state.reloadTimer<=0)finishReload()}if(state.waveState==='spawning'){state.spawnCooldown-=dt;if(state.spawnCooldown<=0&&state.zombiesToSpawn>0){spawnZombie();state.zombiesToSpawn--;state.spawnCooldown=clamp(1.1-state.wave*.045,.28,1.1)}if(state.zombiesToSpawn<=0)state.waveState='active'}if(state.waveState==='active'&&state.zombies.every(z=>z.dead)){state.waveState='between';state.waveTimer=4;floater('WAVE COMPLETE',p.x,p.y,'#ffcf4a')}if(state.waveState==='between'){state.waveTimer-=dt;if(state.waveTimer<=0)nextWave()}for(const z of state.zombies)updateZombie(z,dt);state.zombies=state.zombies.filter(z=>!z.dead||(z.deathT=(z.deathT||.45)-dt)>0);for(const pu of state.powerups){pu.t-=dt;pu.bob+=dt*4;if(dist(p.x,p.y,pu.x,pu.y)<.6){pickupPower(pu);pu.t=-1}}state.powerups=state.powerups.filter(pu=>pu.t>0);for(const f of state.floaters){f.t-=dt;f.z+=dt*.8}state.floaters=state.floaters.filter(f=>f.t>0);state.prompt=findInteractable();updatePrompt();updateHud()}
  function updateZombie(z,dt){if(z.dead)return;z.hurt=Math.max(0,z.hurt-dt);z.anim+=dt*6;const p=state.player,d=dist(z.x,z.y,p.x,p.y);if(d>.28){const direct=Math.atan2(p.y-z.y,p.x-z.x);if(!hasLine(z.x,z.y,p.x,p.y)){const nearDoor=doors.find(dr=>!dr.open&&dist(z.x,z.y,dr.x+.5,dr.y+.5)<.95);if(nearDoor)nearDoor.open=true}let bestA=direct,bestScore=999;for(const a of [direct,direct+.45,direct-.45,direct+1.15,direct-1.15,direct+Math.PI]){const tx=z.x+Math.cos(a)*.35,ty=z.y+Math.sin(a)*.35;if(isWall(tx,ty))continue;const sc=dist(tx,ty,p.x,p.y)+(hasLine(tx,ty,p.x,p.y)?-.25:0);if(sc<bestScore){bestScore=sc;bestA=a}}const sp=z.speed*dt;if(!isWall(z.x+Math.cos(bestA)*sp,z.y))z.x+=Math.cos(bestA)*sp;if(!isWall(z.x,z.y+Math.sin(bestA)*sp))z.y+=Math.sin(bestA)*sp}else{z.attack-=dt;if(z.attack<=0){damagePlayer(z.tier==='brute'?24:16);z.attack=z.tier==='brute'?1.1:.82}}}
  function damagePlayer(n){const now=performance.now();if(now-state.lastHurt<260)return;state.lastHurt=now;state.player.hp-=n;hud.hitFlash.style.opacity=.9;setTimeout(()=>hud.hitFlash.style.opacity=0,120);state.shake=.16;beep(65,.08,'sawtooth',.05);if(state.player.hp<=0)gameOver()} function gameOver(){state.gameOver=true;state.running=false;hud.center.style.display='block';hud.center.innerHTML=`<h1>YOU SURVIVED<br>WAVE ${state.wave}</h1><p>Kills: ${state.player.kills} · Points: $${Math.floor(state.player.points)}. Tap restart and run it back.</p><button id="restartButton">RESTART</button>`;$('restartButton').addEventListener('click',startGame,{passive:true})}
  function tryMove(dx,dy){const p=state.player;if(!isWall(p.x+dx,p.y))p.x+=dx;if(!isWall(p.x,p.y+dy))p.y+=dy}
  function floater(text,x,y,color){state.floaters.push({text,x,y,z:.2,t:1.1,color})}
  function project(x,y){const p=state.player,dx=x-p.x,dy=y-p.y,d=Math.hypot(dx,dy),ang=angleDiff(Math.atan2(dy,dx),p.a),fov=Math.PI/3.05;if(Math.abs(ang)>fov*.72||d<.05)return null;return {sx:(.5+ang/fov)*innerWidth,d}}
  function render(){const w=innerWidth,h=innerHeight;ctx.fillStyle='#080807';ctx.fillRect(0,0,w,h);const p=state.player,shake=state.shake?rand(-state.shake,state.shake)*w*.012:0,horizon=h*.5+shake,grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#11141a');grad.addColorStop(.49,'#070808');grad.addColorStop(.5,'#1a1410');grad.addColorStop(1,'#080604');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.save();ctx.globalAlpha=.33;ctx.drawImage(tex.floor,0,horizon,w,h-horizon);ctx.restore();const fov=Math.PI/3.05,cols=Math.min(w,460),colW=w/cols,zbuf=[];for(let i=0;i<cols;i++){const a=p.a-fov/2+(i/cols)*fov,hit=castRay(p.x,p.y,a),cd=hit.d*Math.cos(a-p.a),wallH=Math.min(h*1.85,h/(cd*.72)),x=i*colW,y=horizon-wallH/2,img=hit.type===2?tex.door:tex.wall,sx=Math.floor((hit.frac||0)*img.width),shade=clamp(1-cd/14,.16,1);ctx.globalAlpha=1;ctx.drawImage(img,sx,0,1,img.height,x,y,colW+1,wallH);ctx.fillStyle=`rgba(0,0,0,${1-shade})`;ctx.fillRect(x,y,colW+1,wallH);zbuf[i]=cd}const things=[];for(const z of state.zombies)things.push({type:'z',obj:z,d:dist(p.x,p.y,z.x,z.y)});for(const pu of state.powerups)things.push({type:'pu',obj:pu,d:dist(p.x,p.y,pu.x,pu.y)});for(const g of wallGuns)things.push({type:'gun',obj:g,d:dist(p.x,p.y,g.x,g.y)});for(const pm of perkMachines)things.push({type:'perk',obj:pm,d:dist(p.x,p.y,pm.x,pm.y)});things.sort((a,b)=>b.d-a.d);for(const it of things)renderThing(it,zbuf,horizon);renderMinimap();renderFloaters();renderWeapon();ctx.globalAlpha=1}
  function renderThing(it,zbuf,horizon){const o=it.obj,pr=project(o.x,o.y);if(!pr||!hasLine(state.player.x,state.player.y,o.x,o.y))return;const scale=innerHeight/(pr.d*.88),col=Math.floor(pr.sx/innerWidth*zbuf.length);if(col>=0&&zbuf[col]&&pr.d>zbuf[col]+.15)return;if(it.type==='z'){const z=o,height=scale*(z.tier==='brute'?1.35:z.tier==='crawler'?.72:1),width=height*(z.tier==='brute'?.62:.5),bob=Math.sin(z.anim)*height*.035,y=horizon-height*.82+bob;drawSpriteCell(ctx,z.cell,pr.sx-width/2,y,width,height,z.dead?.35:1);if(z.hurt>0){ctx.fillStyle='rgba(255,255,255,.45)';ctx.fillRect(pr.sx-width/2,y,width,height)}ctx.fillStyle='rgba(0,0,0,.7)';ctx.fillRect(pr.sx-width*.35,y-10,width*.7,5);ctx.fillStyle=z.tier==='brute'?'#ff5b49':'#63ff9f';ctx.fillRect(pr.sx-width*.35,y-10,width*.7*clamp(z.hp/z.maxHp,0,1),5)}else{let cell=12,size=scale*.42;if(it.type==='gun'){cell=weapons[o.weapon].cell;size=scale*.34}else if(it.type==='perk'){cell=perkDefs[o.perk].cell;size=scale*.31}else if(it.type==='pu'){cell={max:12,insta:13,double:14,nuke:15}[o.type];size=scale*.30}drawSpriteCell(ctx,cell,pr.sx-size/2,horizon-size*(it.type==='pu'?.75:.95)+Math.sin(o.bob||0)*6,size,size)}}
  function renderWeapon(){const wpn=weapons[state.current],w=innerWidth,h=innerHeight,size=Math.min(w*.42,h*.48),bob=Math.sin(performance.now()/120)*4;ctx.save();ctx.translate(w/2,h-size*.36+bob);drawSpriteCell(ctx,wpn.cell,-size/2,-size*.55,size,size*.55);ctx.restore();if(state.reloading){ctx.fillStyle='rgba(0,0,0,.58)';ctx.fillRect(w/2-80,h-92,160,8);ctx.fillStyle='#74c7ff';ctx.fillRect(w/2-80,h-92,160*(1-clamp(state.reloadTimer/(wpn.reloadMs/1000),0,1)),8)}}
  function renderFloaters(){for(const f of state.floaters){const pr=project(f.x,f.y);if(!pr)continue;ctx.globalAlpha=clamp(f.t,0,1);ctx.fillStyle=f.color;ctx.font='900 18px system-ui';ctx.textAlign='center';ctx.fillText(f.text,pr.sx,innerHeight*.48-f.z*80)}ctx.globalAlpha=1}
  function renderMinimap(){const s=4.4,ox=12,oy=innerHeight-96;ctx.save();ctx.globalAlpha=.72;ctx.fillStyle='rgba(0,0,0,.45)';ctx.fillRect(ox-4,oy-4,W*s+8,H*s+8);for(let y=0;y<H;y++)for(let x=0;x<W;x++){if(baseMap[y][x]){ctx.fillStyle='#6d5945';ctx.fillRect(ox+x*s,oy+y*s,s,s)}}for(const d of doors){ctx.fillStyle=d.open?'#2c8050':'#ffcf4a';ctx.fillRect(ox+d.x*s,oy+d.y*s,s,s)}ctx.fillStyle='#63ff9f';ctx.fillRect(ox+state.player.x*s-2,oy+state.player.y*s-2,4,4);ctx.fillStyle='#ff4a3f';for(const z of state.zombies)if(!z.dead)ctx.fillRect(ox+z.x*s-1,oy+z.y*s-1,2,2);ctx.restore()}
  function updatePrompt(){if(state.prompt){hud.prompt.textContent=state.prompt.label+' · Tap BUY / press F';hud.prompt.classList.add('visible')}else hud.prompt.classList.remove('visible')}
  function updateHud(){const p=state.player,w=weapons[state.current],ammo=state.ammo[state.current];hud.health.textContent='❤ '+Math.max(0,Math.ceil(p.hp))+'/'+p.maxHp;hud.points.textContent='$'+Math.floor(p.points);hud.wave.textContent='WAVE '+state.wave;hud.weapon.textContent=w.name;hud.ammo.textContent=state.reloading?'RELOAD '+(Math.ceil(state.reloadTimer*10)/10).toFixed(1):ammo.mag+' / '+ammo.reserve;hud.zombies.textContent='ZOMBIES '+state.zombies.filter(z=>!z.dead).length+(state.zombiesToSpawn?' +'+state.zombiesToSpawn:'');hud.perks.innerHTML='';for(const id of state.perks){const d=perkDefs[id],el=document.createElement('div');el.className='pill';el.style.color=d.color;el.textContent=d.name;hud.perks.appendChild(el)}if(state.activePowers.insta>0||state.activePowers.double>0){const el=document.createElement('div');el.className='pill gold';el.textContent=[state.activePowers.insta>0?'INSTA '+Math.ceil(state.activePowers.insta):'',state.activePowers.double>0?'2X '+Math.ceil(state.activePowers.double):''].filter(Boolean).join(' · ');hud.perks.appendChild(el)}}
  function loop(t){const dt=Math.min(.05,(t-state.last)/1000||0);state.last=t;update(dt);render();requestAnimationFrame(loop)}
  const moveZone=$('moveZone'),lookZone=$('lookZone'),fireButton=$('fireButton'),useButton=$('useButton'),reloadButton=$('reloadButton');
  hud.start.addEventListener('click',startGame,{passive:true}); hud.pause.addEventListener('click',()=>{if(state.running){state.paused=!state.paused;hud.pause.textContent=state.paused?'RESUME':'PAUSE'}},{passive:true});
  fireButton.addEventListener('pointerdown',e=>{touch.firing=true;fire();e.preventDefault()},{passive:false});fireButton.addEventListener('pointerup',()=>touch.firing=false);fireButton.addEventListener('pointercancel',()=>touch.firing=false);useButton.addEventListener('pointerdown',e=>{interact();e.preventDefault()},{passive:false});reloadButton.addEventListener('pointerdown',e=>{reload();e.preventDefault()},{passive:false});
  moveZone.addEventListener('pointerdown',e=>{touch.moveId=e.pointerId;touch.moveStart={x:e.clientX,y:e.clientY};moveZone.setPointerCapture(e.pointerId);e.preventDefault()},{passive:false});moveZone.addEventListener('pointermove',e=>{if(e.pointerId!==touch.moveId||!touch.moveStart)return;const dx=e.clientX-touch.moveStart.x,dy=e.clientY-touch.moveStart.y,len=Math.hypot(dx,dy),max=50;touch.move={x:clamp(dx/max,-1,1),y:clamp(dy/max,-1,1)};if(len>max){touch.move.x=dx/len;touch.move.y=dy/len}hud.nub.style.transform=`translate3d(${touch.move.x*34}px,${touch.move.y*34}px,0)`;e.preventDefault()},{passive:false});function endMove(e){if(e.pointerId===touch.moveId){touch.moveId=null;touch.moveStart=null;touch.move={x:0,y:0};hud.nub.style.transform='translate3d(0,0,0)'}}moveZone.addEventListener('pointerup',endMove);moveZone.addEventListener('pointercancel',endMove);
  lookZone.addEventListener('pointerdown',e=>{touch.lookId=e.pointerId;touch.lookLast={x:e.clientX,y:e.clientY};lookZone.setPointerCapture(e.pointerId);e.preventDefault()},{passive:false});lookZone.addEventListener('pointermove',e=>{if(e.pointerId!==touch.lookId||!touch.lookLast)return;state.player.a+=(e.clientX-touch.lookLast.x)*.0062;touch.lookLast={x:e.clientX,y:e.clientY};e.preventDefault()},{passive:false});function endLook(e){if(e.pointerId===touch.lookId){touch.lookId=null;touch.lookLast=null}}lookZone.addEventListener('pointerup',endLook);lookZone.addEventListener('pointercancel',endLook);
  addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space')fire();if(e.code==='KeyR')reload();if(e.code==='KeyF')interact();if(e.code==='Digit1')switchWeapon(0);if(e.code==='Digit2')switchWeapon(1);if(e.code==='Digit3')switchWeapon(2);if(e.code==='Digit4')switchWeapon(3)});addEventListener('keyup',e=>keys.delete(e.code));function switchWeapon(i){const id=state.owned[i];if(id){state.current=id;state.reloading=false;updateHud()}}
  function unlockAudio(){if(state.audioReady)return;try{state.audio=new (window.AudioContext||window.webkitAudioContext)();state.audioReady=true}catch{}} function beep(freq,dur,type='sine',gain=.025){if(!state.audioReady||!state.audio)return;const o=state.audio.createOscillator(),g=state.audio.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(state.audio.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,state.audio.currentTime+dur);o.stop(state.audio.currentTime+dur)}
  window.__pocketZombiesDebug=()=>({running:state.running,wave:state.wave,zombies:state.zombies.length,sheetReady,weapon:state.current,ammo:state.ammo[state.current]}); updateHud(); requestAnimationFrame(loop); console.log('[Pocket Zombies] Loaded asset-backed build.');
})();

