import { escapeHtml, loading, pageHeading, card, statusPill, relativeTime, emptyState } from '../../ui/page-kit.js';

export async function mountGatewaysPage({shell,gateways}){
  shell.setActiveTab('chat');shell.setTitle('Connections');const page=shell.page;let disposed=false;
  async function render(){
    page.innerHTML=`${pageHeading('Gateway Connections','Your Prometheus computers',`<button class="pm-btn primary" data-add-gateway>Add</button><button class="pm-btn ghost" data-probe>Refresh</button>`)}${loading('Checking gateways…')}`;
    const probed=await gateways.probeAll();if(disposed)return;const rows=probed.filter(Boolean);
    page.innerHTML=`${pageHeading('Gateway Connections','Your Prometheus computers',`<button class="pm-btn primary" data-add-gateway>Add</button><button class="pm-btn ghost" data-probe>Refresh</button>`)}<div class="pm-v2-card-list">${rows.length?rows.map(entry=>card('',`<div class="pm-v2-row-between"><div><strong>${escapeHtml(entry.name)}</strong><small>${escapeHtml(entry.origin)}</small></div>${statusPill(entry.status||'unknown')}</div><div class="pm-v2-gateway-meta"><span>${escapeHtml(entry.platform||'')}</span><span>${escapeHtml(entry.version||'')}</span><span>${entry.lastSeenAt?escapeHtml(relativeTime(entry.lastSeenAt)):''}</span></div><div class="pm-v2-actions"><button class="pm-btn ${entry.id===gateways.activeId?'primary':'ghost'}" data-select-gateway="${escapeHtml(entry.id)}">${entry.id===gateways.activeId?'Selected':'Use gateway'}</button><button class="pm-btn ghost" data-repair-gateway="${escapeHtml(entry.id)}">Reconnect</button>${entry.origin!==window.location.origin?`<button class="pm-btn ghost danger" data-forget-gateway="${escapeHtml(entry.id)}">Forget</button>`:''}</div>`)).join(''):emptyState('No gateways paired')}</div>`;
    page.querySelector('[data-add-gateway]')?.addEventListener('click',()=>shell.navigate?.('pair/add'));page.querySelector('[data-probe]')?.addEventListener('click',render);page.querySelectorAll('[data-select-gateway]').forEach(b=>b.addEventListener('click',()=>{gateways.select(b.dataset.selectGateway);shell.showNotice(`Using ${gateways.activeEntry?.name||'gateway'}.`);render();}));page.querySelectorAll('[data-repair-gateway]').forEach(b=>b.addEventListener('click',()=>shell.navigate?.(`pair/${encodeURIComponent(b.dataset.repairGateway)}`)));page.querySelectorAll('[data-forget-gateway]').forEach(b=>b.addEventListener('click',()=>{if(confirm('Forget this gateway on this phone?')){gateways.forget(b.dataset.forgetGateway);render();}}));
  }
  render();return()=>{disposed=true;};
}
