import { escapeHtml, loading, emptyState, errorState, pageHeading, statusPill, card, tabs, safeJson, relativeTime } from '../../ui/page-kit.js';
import { mountStreamChatPanel } from '../shared/stream-chat-panel.js';

const TEAM_TABS=[['context','Context'],['subagents','Subagents'],['workspace','Workspace'],['memory','Memory'],['runs','Runs'],['chat','Team Chat']].map(([id,label])=>({id,label}));
function teamName(team){return String(team?.name||team?.title||team?.id||'Team');}
function teamStatus(team){return String(team?.status||team?.roomState?.status||(team?.paused?'paused':'active'));}
function members(team){return Array.isArray(team?.members)?team.members:Array.isArray(team?.subagents)?team.subagents:Array.isArray(team?.subagentIds)?team.subagentIds.map((id)=>({id,name:id})):[];}

export async function mountTeamsPage({shell,features,route}){
  shell.setActiveTab('chat'); shell.setTitle(route?.id?'Team':'Teams'); const page=shell.page; let disposed=false; let chatCleanup=()=>{};
  async function list(){
    chatCleanup(); page.innerHTML=`${pageHeading('Teams','Managed multi-agent groups')}${loading('Loading teams…')}`;
    try{const rows=await features.teams();if(disposed)return;page.innerHTML=`${pageHeading('Teams','Managed multi-agent groups',`<button class="pm-btn ghost" data-team-refresh>Refresh</button>`)}<div class="pm-v2-card-list">${rows.length?rows.map((team)=>card('',`<button class="pm-v2-card-link" data-team-id="${escapeHtml(team.id)}"><div class="pm-v2-row-between"><strong>${escapeHtml(teamName(team))}</strong>${statusPill(teamStatus(team))}</div><p>${escapeHtml(team.purpose||team.description||team.currentTask||'')}</p><small>${members(team).length} agent${members(team).length===1?'':'s'}${team.lastRunAt?` • ${escapeHtml(relativeTime(team.lastRunAt))}`:''}</small></button>`)).join(''):emptyState('No teams','Create teams on desktop or through Prometheus.')}</div>`;page.querySelector('[data-team-refresh]')?.addEventListener('click',list);page.querySelectorAll('[data-team-id]').forEach(b=>b.addEventListener('click',()=>shell.navigate?.(`teams/${encodeURIComponent(b.dataset.teamId)}`)));}catch(error){page.innerHTML=`${pageHeading('Teams')}${errorState(error)}`;page.querySelector('[data-v2-retry]')?.addEventListener('click',list);}
  }
  async function detail(id,active='context'){
    chatCleanup(); page.innerHTML=`${pageHeading('Team')}${loading('Loading team…')}`;
    try{const rows=await features.teams();const team=rows.find(t=>String(t.id)===String(id));if(!team)throw new Error('Team not found.'); if(disposed)return;
      const actionStatus=teamStatus(team); const primary=/paused/i.test(actionStatus)?'resume':'pause';
      const base=()=>`${pageHeading(teamName(team),team.purpose||team.description||'',`<button class="pm-btn ghost" data-team-back>Back</button>`)}<div class="pm-v2-actions pm-v2-action-bar"><button class="pm-btn primary" data-team-action="start">Start run</button><button class="pm-btn ghost" data-team-action="${primary}">${primary==='pause'?'Pause':'Resume'}</button><button class="pm-btn ghost" data-team-action="review">Review</button><button class="pm-btn ghost danger" data-team-action="delete">Delete</button></div>${tabs(TEAM_TABS,active)}<div class="pm-v2-tab-content" data-team-tab-content></div>`;
      page.innerHTML=base();
      const host=page.querySelector('[data-team-tab-content]');
      async function renderTab(tab){active=tab;page.querySelectorAll('[data-v2-tab]').forEach(b=>b.classList.toggle('active',b.dataset.v2Tab===active));chatCleanup();chatCleanup=()=>{};
        if(active==='context'){
          const refs=Array.isArray(team.contextReferences)?team.contextReferences:Array.isArray(team.contextRefs)?team.contextRefs:[];
          host.innerHTML=`${card('Current task',`<p>${escapeHtml(team.currentTask||team.task||'No current task.')}</p>`)}${card('Purpose',`<p>${escapeHtml(team.purpose||team.description||'No purpose recorded.')}</p>`)}${refs.length?card('Context references',`<div class="pm-v2-event-list">${refs.map(r=>`<div><strong>${escapeHtml(r.title||r.name||'Reference')}</strong><span>${escapeHtml(r.body||r.summary||r.url||'')}</span></div>`).join('')}</div>`):''}${card('Add context',`<form data-team-context class="pm-v2-inline-form"><input class="pm-input" name="title" placeholder="Title"/><textarea class="pm-input" name="body" placeholder="Context for the team"></textarea><button class="pm-btn primary">Save</button></form>`)}`;
          host.querySelector('[data-team-context]')?.addEventListener('submit',async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await features.saveTeamContext(id,String(f.get('title')||''),String(f.get('body')||''));shell.showNotice('Team context saved.');detail(id,'context');}catch(err){shell.showNotice(err?.message||'Save failed.');}});
        } else if(active==='subagents'){
          const list=members(team);host.innerHTML=list.length?`<div class="pm-v2-card-list">${list.map(m=>card('',`<button class="pm-v2-card-link" data-agent-id="${escapeHtml(m.id||m.agentId||m.name)}"><div class="pm-v2-row-between"><strong>${escapeHtml(m.name||m.label||m.id||'Agent')}</strong>${statusPill(m.status||m.state||'member')}</div><small>${escapeHtml(m.model||m.role||'')}</small></div></button>`)).join('')}</div>`:emptyState('No team members');host.querySelectorAll('[data-agent-id]').forEach(b=>b.addEventListener('click',()=>shell.navigate?.(`subagents/${encodeURIComponent(b.dataset.agentId)}`)));
        } else if(active==='workspace'){
          host.innerHTML=loading('Loading workspace…');const data=await features.teamWorkspace(id);if(disposed)return;const files=data.files||[];host.innerHTML=files.length?`<div class="pm-v2-file-list">${files.map(f=>{const p=typeof f==='string'?f:f.path||f.relpath||f.name;return `<button data-team-file="${escapeHtml(p)}">${escapeHtml(p)}</button>`}).join('')}</div><pre class="pm-v2-pre" data-team-file-content>Select a file.</pre>`:emptyState('No workspace files');host.querySelectorAll('[data-team-file]').forEach(b=>b.addEventListener('click',async()=>{const target=host.querySelector('[data-team-file-content]');target.textContent='Loading…';try{const r=await features.teamWorkspaceFile(id,b.dataset.teamFile);target.textContent=String(r?.content??safeJson(r));}catch(err){target.textContent=err?.message||'Failed to load file.';}}));
        } else if(active==='memory'){
          const data=await features.teamWorkspace(id);const files=(data.files||[]).filter(f=>/memory|last[-_ ]?run|pending/i.test(typeof f==='string'?f:f.path||f.name||''));host.innerHTML=files.length?`<div class="pm-v2-file-list">${files.map(f=>{const p=typeof f==='string'?f:f.path||f.name;return `<button data-memory-file="${escapeHtml(p)}">${escapeHtml(p)}</button>`}).join('')}</div><pre class="pm-v2-pre" data-memory-content>Select a memory file.</pre>`:emptyState('No team memory files','This team has not written memory artifacts yet.');host.querySelectorAll('[data-memory-file]').forEach(b=>b.addEventListener('click',async()=>{const target=host.querySelector('[data-memory-content]');const r=await features.teamWorkspaceFile(id,b.dataset.memoryFile).catch(err=>({content:err.message}));target.textContent=String(r?.content??safeJson(r));}));
        } else if(active==='runs'){
          host.innerHTML=loading('Loading runs…');const data=await features.teamRuns(id);const runs=data.runs||[];host.innerHTML=runs.length?`<div class="pm-v2-event-list">${runs.map(run=>`<div><strong>${escapeHtml(run.title||run.task||run.id||'Run')}</strong><span>${escapeHtml(run.status||run.state||'')} ${run.startedAt?`• ${escapeHtml(relativeTime(run.startedAt))}`:''}</span></div>`).join('')}</div>`:emptyState('No runs yet');
        } else if(active==='chat'){
          host.innerHTML='<div data-team-chat></div>';chatCleanup=mountStreamChatPanel({host:host.querySelector('[data-team-chat]'),loadMessages:()=>features.teamChat(id),streamMessage:(message,opts)=>features.streamTeamChat(id,message,opts),placeholder:'Message the team…',emptyLabel:'Start the team room conversation.'});
        }
      }
      page.querySelector('[data-team-back]')?.addEventListener('click',()=>shell.navigate?.('teams'));page.querySelectorAll('[data-v2-tab]').forEach(b=>b.addEventListener('click',()=>renderTab(b.dataset.v2Tab)));page.querySelectorAll('[data-team-action]').forEach(b=>b.addEventListener('click',async()=>{const action=b.dataset.teamAction;if(action==='delete'&&!confirm(`Delete ${teamName(team)}?`))return;try{await features.teamAction(id,action);shell.showNotice(`${action} requested.`);if(action==='delete')shell.navigate?.('teams');else detail(id,active);}catch(err){shell.showNotice(err?.message||'Team action failed.');}}));renderTab(active);
    }catch(error){page.innerHTML=`${pageHeading('Team')}${errorState(error)}`;}
  }
  if(route?.id)detail(route.id,route?.sub||'context');else list();return()=>{disposed=true;chatCleanup();};
}
