import { escapeHtml, pageHeading, card, loading } from '../../ui/page-kit.js';

const THEMES=[['dark','Prometheus One'],['gray','Ash & Ember'],['blue','Olympian Blue'],['purple','Aether Violet']];
function currentTheme(){try{return localStorage.getItem('prometheus_theme')||document.documentElement.getAttribute('data-skin')||'dark';}catch{return'dark';}}
function applyTheme(id){const key=THEMES.some(([value])=>value===id)?id:'dark';document.documentElement.setAttribute('data-skin',key);document.documentElement.setAttribute('data-theme','dark');try{localStorage.setItem('prometheus_theme',key);}catch{}document.dispatchEvent(new CustomEvent('prom-theme-change',{detail:{id:key,base:'dark'}}));}

export async function mountSettingsPage({shell,features,gateways}){
  shell.setActiveTab('chat');shell.setTitle('Settings');const page=shell.page;let disposed=false;
  page.innerHTML=`${pageHeading('Settings','Mobile V2')}${loading('Loading settings…')}`;const[heartbeat,status,voice]=await Promise.all([features.heartbeat(),features.status(),features.voiceStatus().catch(()=>null)]);if(disposed)return;const hb=heartbeat?.heartbeat||heartbeat?.config||heartbeat||{};
  page.innerHTML=`${pageHeading('Settings','Mobile V2')}${card('Appearance',`<label class="pm-v2-field"><span>Theme</span><select class="pm-select" data-theme>${THEMES.map(([id,label])=>`<option value="${id}" ${currentTheme()===id?'selected':''}>${label}</option>`).join('')}</select></label>`)}${card('Gateway',`<div class="pm-v2-event-list"><div><strong>${escapeHtml(gateways.activeEntry?.name||'This gateway')}</strong><span>${escapeHtml(gateways.activeEntry?.origin||'')}</span></div><div><strong>Model</strong><span>${escapeHtml(status?.actualModel||status?.currentModel||status?.configuredModel||'Default')}</span></div></div><div class="pm-v2-actions"><button class="pm-btn ghost" data-open-gateways>Gateway Connections</button></div>`)}${card('Heartbeat',`<form class="pm-v2-form" data-heartbeat-form><label class="pm-v2-check"><input type="checkbox" name="enabled" ${hb.enabled!==false?'checked':''}/><span>Enabled</span></label><label class="pm-v2-field"><span>Interval minutes</span><input type="number" min="1" max="1440" name="interval_minutes" value="${escapeHtml(hb.interval_minutes??hb.intervalMinutes??60)}"/></label><label class="pm-v2-field"><span>Model</span><input name="model" value="${escapeHtml(hb.model||'')}" placeholder="Default model"/></label><label class="pm-v2-field"><span>Instructions</span><textarea name="instructions" rows="7">${escapeHtml(hb.instructions||'')}</textarea></label><button class="pm-btn primary">Save heartbeat</button></form>`)}${card('Voice',`<div class="pm-v2-event-list"><div><strong>Speech</strong><span>${escapeHtml(voice?.voice?.configured===false?'Needs setup':'Ready')}</span></div><div><strong>Realtime</strong><span>${escapeHtml(voice?.realtime?.configured?'Available':'Fallback mode')}</span></div></div><button class="pm-btn ghost" data-open-voice>Open Voice</button>`)}${card('Maintenance',`<div class="pm-v2-actions"><button class="pm-btn ghost" data-clear-v2-cache>Clear V2 local UI state</button></div><p class="pm-v2-muted">This does not delete chats or gateway-owned data.</p>`)}`;
  page.querySelector('[data-theme]')?.addEventListener('change',(e)=>applyTheme(e.target.value));page.querySelector('[data-open-gateways]')?.addEventListener('click',()=>shell.navigate?.('gateways'));page.querySelector('[data-open-voice]')?.addEventListener('click',()=>shell.navigate?.('voice'));page.querySelector('[data-heartbeat-form]')?.addEventListener('submit',async(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await features.saveHeartbeat({enabled:f.get('enabled')==='on',interval_minutes:Number(f.get('interval_minutes')||60),model:String(f.get('model')||''),instructions:String(f.get('instructions')||'')});shell.showNotice('Heartbeat settings saved.');}catch(error){shell.showNotice(error?.message||'Could not save heartbeat.');}});page.querySelector('[data-clear-v2-cache]')?.addEventListener('click',()=>{try{Object.keys(localStorage).filter(k=>k.startsWith('pm_mobile_v2_')).forEach(k=>localStorage.removeItem(k));}catch{}shell.showNotice('V2 local UI state cleared.');});return()=>{disposed=true;};
}
