import { escapeHtml, pageHeading, card, loading, emptyState } from '../../ui/page-kit.js';

const MENU=[['gateways','Gateway Connections','Manage paired Prometheus computers'],['settings','Settings','Theme, heartbeat, voice, and mobile preferences'],['memory','Memory','Associative memory graph and recent entries'],['audit','Audit','Recent non-main activity'],['creative','Creative','Image and video generation studio']];

export function mountMorePage({shell}){shell.setActiveTab('chat');shell.setTitle('More');const page=shell.page;page.innerHTML=`${pageHeading('More','Prometheus mobile tools')}<div class="pm-v2-menu-list">${MENU.map(([route,title,subtitle])=>`<button data-more-route="${route}"><strong>${title}</strong><span>${subtitle}</span><b>›</b></button>`).join('')}</div>`;page.querySelectorAll('[data-more-route]').forEach(b=>b.addEventListener('click',()=>shell.navigate?.(b.dataset.moreRoute)));return()=>{};}

export async function mountCreativePage({shell,features,gateways}){shell.setActiveTab('chat');shell.setTitle('Creative');const page=shell.page;let mode='image';let busy=false;let sessionId=`mobile_v2_creative_${mode}`;
  async function loadGallery(){const host=page.querySelector('[data-creative-gallery]');if(!host)return;host.innerHTML=loading('Loading gallery…');try{const data=await features.creativeGallery(mode);host.innerHTML=data.length?`<div class="pm-v2-media-grid">${data.slice(0,24).map(item=>{const path=item.path||item.relPath||item.name||'';const url=gateways.active.inlineMediaUrl(path);return `<figure>${mode==='video'?`<video src="${escapeHtml(url)}" controls playsinline preload="metadata"></video>`:`<img src="${escapeHtml(url)}" alt="${escapeHtml(item.name||'Generated image')}" loading="lazy"/>`}<figcaption>${escapeHtml(item.name||path.split('/').pop()||'Output')}</figcaption></figure>`}).join('')}</div>`:emptyState('No generated media',`Generate your first ${mode}.`);}catch(error){host.innerHTML=`<div class="pm-v2-error-card">${escapeHtml(error?.message||'Gallery unavailable.')}</div>`;}}
  function paint(){page.innerHTML=`${pageHeading('Creative Studio','Generate images and video with Prometheus')}<div class="pm-v2-segment"><button class="${mode==='image'?'active':''}" data-mode="image">Image</button><button class="${mode==='video'?'active':''}" data-mode="video">Video</button></div>${card('',`<form class="pm-v2-form" data-creative-form><textarea class="pm-input" rows="5" placeholder="Describe what you want to create…"></textarea><label class="pm-v2-field"><span>Provider</span><select class="pm-select" name="provider"><option value="auto">Auto</option><option value="openai">OpenAI</option><option value="xai">xAI</option><option value="hf">HyperFrames</option></select></label><button class="pm-btn primary" ${busy?'disabled':''}>${busy?'Generating…':`Generate ${mode}`}</button></form><div class="pm-v2-prose" data-creative-result></div>`)}<h2 class="pm-v2-section-title">Recent outputs</h2><div data-creative-gallery></div>`;page.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;sessionId=`mobile_v2_creative_${mode}`;paint();loadGallery();}));page.querySelector('[data-creative-form]')?.addEventListener('submit',generate);loadGallery();}
  async function generate(event){event.preventDefault();if(busy)return;const prompt=event.currentTarget.querySelector('textarea').value.trim();const provider=new FormData(event.currentTarget).get('provider');if(!prompt)return;busy=true;paint();const result=page.querySelector('[data-creative-result]');let answer='';try{const gateway=gateways.active;try{await gateway.createSession({id:sessionId,title:'Creative Studio'});}catch{}await gateway.streamChat({sessionId,message:`Create a ${mode} using the ${provider} provider if available. User request: ${prompt}`,clientRequestId:`creative_${Date.now()}`,onEvent:(e)=>{if(e.type==='assistant.delta'){answer+=e.text||'';result.textContent=answer;}else if(e.type==='assistant.done'&&e.text&&!answer){answer=e.text;result.textContent=answer;}}});shell.showNotice(`${mode==='image'?'Image':'Video'} generation request finished.`);setTimeout(loadGallery,800);}catch(error){result.textContent=error?.message||'Generation failed.';}finally{busy=false;setTimeout(()=>{const button=page.querySelector('[data-creative-form] button[type="submit"]');if(button){button.disabled=false;button.textContent=`Generate ${mode}`;}},0);}}
  paint();return()=>{};
}
