import { escapeHtml, pageHeading, card, loading, emptyState } from '../../ui/page-kit.js';
const MENU=[['gateways','Gateway Connections','Manage paired Prometheus computers'],['settings','Settings','Theme, heartbeat, voice, and mobile preferences'],['memory','Memory','Associative memory graph and recent entries'],['audit','Audit','Recent non-main activity'],['creative','Creative','Image and video generation studio']];
export function mountMorePage({shell}){shell.setActiveTab('chat');shell.setTitle('More');const page=shell.page;page.innerHTML=`${pageHeading('More','Prometheus mobile tools')}<div class="pm-v2-menu-list">${MENU.map(([route,title,subtitle])=>`<button data-more-route="${route}"><strong>${title}</strong><span>${subtitle}</span><b>›</b></button>`).join('')}</div>`;page.querySelectorAll('[data-more-route]').forEach(button=>button.addEventListener('click',()=>shell.navigate(button.dataset.moreRoute)));return()=>{};}
function flattenGallery(body,kind){const output=[];const visit=(value)=>{if(!value)return;if(Array.isArray(value)){value.forEach(visit);return;}if(typeof value==='string'){output.push({name:value.split('/').pop(),path:value});return;}if(typeof value!=='object')return;const path=String(value.path||value.relPath||value.relativePath||value.file||'');const name=String(value.name||path.split('/').pop()||'');const type=String(value.type||value.kind||'').toLowerCase();if(path&&type!=='directory'&&type!=='dir')output.push({...value,name,path});for(const key of ['files','children','items','entries','tree'])if(value[key])visit(value[key]);};visit(body);const unique=new Map();for(const item of output){const path=String(item.path||'');if(!path)continue;const ext=path.toLowerCase();if(kind==='video'&&!/\.(mp4|webm|mov|m4v|gif)$/.test(ext))continue;if(kind==='image'&&!/\.(png|jpe?g|webp|gif|avif)$/.test(ext))continue;unique.set(path,item);}return[...unique.values()].sort((a,b)=>Number(b.mtime||b.updatedAt||0)-Number(a.mtime||a.updatedAt||0));}
async function creativeGallery(gateway,kind){const root=kind==='video'?'generated/videos':'generated/images';const body=await gateway.request(`/api/canvas/files?root=${encodeURIComponent(root)}`);return flattenGallery(body,kind);}
export async function mountCreativePage({shell,gateways}){shell.setActiveTab('chat');shell.setTitle('Creative');const page=shell.page;let mode='image';let busy=false;let sessionId=`mobile_v2_creative_${mode}`;let disposed=false;
  async function loadGallery(){const host=page.querySelector('[data-creative-gallery]');if(!host)return;host.innerHTML=loading('Loading gallery…');try{const gateway=gateways.active;const data=await creativeGallery(gateway,mode);if(disposed)return;host.innerHTML=data.length?`<div class="pm-v2-media-grid">${data.slice(0,24).map(item=>{const path=item.path||'';const url=gateway.inlineMediaUrl(path);return`<figure>${mode==='video'?`<video src="${escapeHtml(url)}" controls playsinline preload="metadata"></video>`:`<img src="${escapeHtml(url)}" alt="${escapeHtml(item.name||'Generated image')}" loading="lazy"/>`}<figcaption>${escapeHtml(item.name||path.split('/').pop()||'Output')}</figcaption></figure>`;}).join('')}</div>`:emptyState('No generated media',`Generate your first ${mode}.`);}catch(error){host.innerHTML=`<div class="pm-v2-error-card">${escapeHtml(error?.message||'Gallery unavailable.')}</div>`;}}
  function paint(){page.innerHTML=`${pageHeading('Creative Studio','Generate images and video with Prometheus')}<div class="pm-v2-segment"><button class="${mode==='image'?'active':''}" data-mode="image">Image</button><button class="${mode==='video'?'active':''}" data-mode="video">Video</button></div>${card('',`<form class="pm-v2-form" data-creative-form><textarea class="pm-input" rows="5" placeholder="Describe what you want to create…"></textarea><label class="pm-v2-field"><span>Provider</span><select class="pm-select" name="provider"><option value="auto">Auto</option><option value="openai">OpenAI</option><option value="xai">xAI</option><option value="hf">HyperFrames</option></select></label><button class="pm-btn primary" ${busy?'disabled':''}>${busy?'Generating…':`Generate ${mode}`}</button></form><div class="pm-v2-prose" data-creative-result></div>`)}<h2 class="pm-v2-section-title">Recent outputs</h2><div data-creative-gallery></div>`;page.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{mode=button.dataset.mode;sessionId=`mobile_v2_creative_${mode}`;paint();loadGallery();}));page.querySelector('[data-creative-form]')?.addEventListener('submit',generate);loadGallery();}
  async function generate(event){event.preventDefault();if(busy)return;const prompt=event.currentTarget.querySelector('textarea').value.trim();const provider=new FormData(event.currentTarget).get('provider');if(!prompt)return;busy=true;const button=event.currentTarget.querySelector('button[type="submit"]');button.disabled=true;button.textContent='Generating…';const result=page.querySelector('[data-creative-result]');let answer='';try{const gateway=gateways.active;try{await gateway.createSession({id:sessionId,title:'Creative Studio'});}catch{}await gateway.streamChat({sessionId,message:`Create a ${mode} using the ${provider} provider if available. User request: ${prompt}`,clientRequestId:`creative_${Date.now()}`,onEvent:event=>{if(event.type==='assistant.delta'){answer+=event.text||'';result.textContent=answer;}else if(event.type==='assistant.done'&&event.text&&!answer){answer=event.text;result.textContent=answer;}}});shell.showNotice(`${mode==='image'?'Image':'Video'} generation request finished.`);setTimeout(loadGallery,900);}catch(error){result.textContent=error?.message||'Generation failed.';}finally{busy=false;if(button.isConnected){button.disabled=false;button.textContent=`Generate ${mode}`;}}}
  paint();return()=>{disposed=true;};
}
