import http from 'node:http';
import { createReadStream, existsSync, statSync } from 'node:fs';
import { extname, join, normalize } from 'node:path';
import { createHash, randomBytes } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('.', import.meta.url));
const PORT = Number(process.env.PORT || 8780);
const rooms = new Map();
const mime = {'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
const code = () => `F8-${randomBytes(2).toString('hex').toUpperCase()}`;
const safeName = value => String(value || 'Driver').replace(/[^a-z0-9 _-]/gi,'').trim().slice(0,18) || 'Driver';
function roomView(room){return {code:room.code,hostId:room.hostId,builderId:room.builderId,phase:room.phase||'lobby',track:room.track,players:[...room.players.values()].map(({id,name,color})=>({id,name,color}))};}
function publicRooms(){return [...rooms.values()].map(room=>({code:room.code,host:room.players.get(room.hostId)?.name||'Host',players:room.players.size,maxPlayers:6,phase:room.phase||'lobby'}));}

function send(socket,msg){if(!socket.destroyed) socket.write(encode(JSON.stringify(msg)));}
function broadcast(room,msg,except){for(const player of room.players.values())if(player.socket !== except)send(player.socket,msg)}
function emitRoom(room){broadcast(room,{type:'room',room:roomView(room)});}
function encode(text){const payload=Buffer.from(text), len=payload.length;let header;if(len<126)header=Buffer.from([0x81,len]);else if(len<65536){header=Buffer.alloc(4);header[0]=0x81;header[1]=126;header.writeUInt16BE(len,2)}else{header=Buffer.alloc(10);header[0]=0x81;header[1]=127;header.writeBigUInt64BE(BigInt(len),2)}return Buffer.concat([header,payload]);}
function frames(socket,onText){let buffer=Buffer.alloc(0);socket.on('data',chunk=>{buffer=Buffer.concat([buffer,chunk]);while(buffer.length>=2){const first=buffer[0],masked=(buffer[1]&128)!==0;let len=buffer[1]&127,at=2;if(len===126){if(buffer.length<4)return;len=buffer.readUInt16BE(2);at=4}else if(len===127){if(buffer.length<10)return;len=Number(buffer.readBigUInt64BE(2));at=10}const maskBytes=masked?4:0;if(buffer.length<at+maskBytes+len)return;const mask=masked?buffer.subarray(at,at+4):null;at+=maskBytes;const payload=Buffer.from(buffer.subarray(at,at+len));buffer=buffer.subarray(at+len);if(mask)for(let i=0;i<payload.length;i++)payload[i]^=mask[i%4];if((first&15)===8){socket.end();return}if((first&15)===1)try{onText(JSON.parse(payload.toString()))}catch{}}});}
const server=http.createServer((req,res)=>{const requestUrl=new URL(req.url,'http://local');if(requestUrl.pathname==='/api/rooms'){res.writeHead(200,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify({rooms:publicRooms()}));return}let path=decodeURIComponent(requestUrl.pathname);if(path==='/'||path==='/figure-8-drift/'||path==='/figure-8-drift')path='/index.html';path=normalize(path).replace(/^([.][.][\\/])+/, '').replace(/^[/\\]+/,'');const file=join(ROOT,path);if(!file.startsWith(ROOT)||!existsSync(file)||statSync(file).isDirectory()){res.writeHead(404);res.end('Not found');return}res.writeHead(200,{'Content-Type':mime[extname(file)]||'application/octet-stream','Cache-Control':'no-store'});createReadStream(file).pipe(res);});
server.on('upgrade',(req,socket)=>{if(req.headers.upgrade?.toLowerCase()!=='websocket'){socket.destroy();return}const key=req.headers['sec-websocket-key'];if(!key){socket.destroy();return}const accept=createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');socket.write(`HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${accept}\r\n\r\n`);let player,room;const leave=()=>{if(!player||!room)return;room.players.delete(player.id);if(room.builderId===player.id)room.builderId=null;if(room.hostId===player.id)room.hostId=room.players.keys().next().value||null;if(room.players.size){emitRoom(room)}else rooms.delete(room.code);player=null;room=null;};frames(socket,msg=>{if(msg.type==='host'){leave();let c=code();while(rooms.has(c))c=code();room={code:c,hostId:null,builderId:null,phase:'lobby',track:{segments:[{type:'preset'}],trackClosed:true,isPreset:true},players:new Map()};rooms.set(c,room);player={id:randomBytes(6).toString('hex'),name:safeName(msg.name),color:msg.color||'#ff5138',socket};room.hostId=player.id;room.players.set(player.id,player);send(socket,{type:'joined',you:player.id,room:roomView(room)});return}if(msg.type==='join'){leave();room=rooms.get(String(msg.code||'').trim().toUpperCase());if(!room){send(socket,{type:'error',message:'Room not found. Check the code and Wi-Fi.'});return}if(room.players.size>=6){send(socket,{type:'error',message:'This room is full (6 drivers).'});room=null;return}player={id:randomBytes(6).toString('hex'),name:safeName(msg.name),color:msg.color||'#54c8ff',socket};room.players.set(player.id,player);send(socket,{type:'joined',you:player.id,room:roomView(room)});emitRoom(room);return}if(!player||!room)return;if(msg.type==='phase'&&player.id===room.hostId&&(msg.phase==='build'||msg.phase==='race')){room.phase=msg.phase;room.builderId=msg.phase==='build'?room.hostId:null;broadcast(room,{type:'phase',phase:room.phase});emitRoom(room);return}if(msg.type==='claimBuild'){if(room.phase!=='build')return;room.builderId=player.id;emitRoom(room);return}if(msg.type==='releaseBuild'&&room.builderId===player.id){room.builderId=null;emitRoom(room);return}if(msg.type==='track'&&room.builderId===player.id&&msg.track&&Array.isArray(msg.track.segments)){room.track={segments:msg.track.segments.slice(0,160),trackClosed:!!msg.track.trackClosed,isPreset:!!msg.track.isPreset};broadcast(room,{type:'track',track:room.track},socket);return}if(msg.type==='car'&&msg.state){const s=msg.state;broadcast(room,{type:'car',id:player.id,state:{x:+s.x||0,z:+s.z||0,yaw:+s.yaw||0,speed:+s.speed||0,lap:+s.lap||0,t:Date.now()}},socket);}});socket.on('close',leave);socket.on('error',leave);});
server.listen(PORT,'0.0.0.0',()=>console.log(`Figure 8 Drift LAN server: http://0.0.0.0:${PORT}/`));
