import type { ConnectionAdapter, ConnectionAdapterContext, ConnectionAdapterResult, ConnectionRecord, ConnectionStrategy, ConnectionVerificationResult } from '../types.js';
export interface CliLoginHost { launch(context: ConnectionAdapterContext, command: string, args: string[]): Promise<void>; status(context: ConnectionAdapterContext): Promise<{ connected: boolean; details?: Record<string, unknown> }>; logout?(context: ConnectionAdapterContext, connection: ConnectionRecord): Promise<void>; }
export class CliLoginConnectionAdapter implements ConnectionAdapter {
  readonly id = 'cli-login'; readonly kind = 'cli-login'; readonly displayName = 'CLI login'; readonly priority = 55;
  constructor(private readonly host: CliLoginHost) {}
  supports(strategy: ConnectionStrategy): boolean { return strategy.adapter === 'cli-login'; }
  async connect(context: ConnectionAdapterContext): Promise<ConnectionAdapterResult> { const config = context.attempt.plan?.strategy.configuration || {}; const command = typeof config.command === 'string' ? config.command : ''; const args = Array.isArray(config.args) ? config.args.map(String) : []; if (!command) return { state: 'failed', error: { code: 'CLI_COMMAND_REQUIRED', message: 'CLI login command is required.', phase: 'planning' } }; await this.host.launch(context, command, args); return { state: 'awaiting_cli_login', userAction: { type: 'cli-login', label: `Sign in to ${context.attempt.serviceName || context.attempt.serviceId}`, commandPreview: [command, ...args].join(' '), completionHint: 'Complete password, MFA, or device authorization directly in the trusted terminal.' } }; }
  async continue(context: ConnectionAdapterContext): Promise<ConnectionAdapterResult> { const state = await this.host.status(context); return state.connected ? { state: 'registering', connection: { authenticated: true, authState: 'healthy', configuration: state.details } } : { state: 'awaiting_cli_login' }; }
  async verify(context: ConnectionAdapterContext, connection: ConnectionRecord): Promise<ConnectionVerificationResult[]> { const state = await this.host.status(context); return [{ id: `${connection.id}:cli`, check: 'cli.authentication', passed: state.connected, details: state.details, verifiedAt: new Date().toISOString() }]; }
  async disconnect(context: ConnectionAdapterContext, connection: ConnectionRecord): Promise<void> { await this.host.logout?.(context, connection); }
}
