import type { ConnectionAdapter, ConnectionAdapterContext, ConnectionAdapterResult, ConnectionRecord, ConnectionStrategy, ConnectionVerificationResult } from '../types.js';
export interface CustomHttpHost { probe(context: ConnectionAdapterContext, configuration: Record<string, unknown>): Promise<{ ok: boolean; status?: number; details?: Record<string, unknown>; error?: string }>; register(context: ConnectionAdapterContext, configuration: Record<string, unknown>): Promise<Record<string, unknown>>; unregister?(context: ConnectionAdapterContext, connection: ConnectionRecord): Promise<void>; }
export class CustomHttpConnectionAdapter implements ConnectionAdapter {
  readonly id = 'custom-http'; readonly kind = 'custom-http'; readonly displayName = 'Custom HTTP endpoint'; readonly priority = 45;
  constructor(private readonly host: CustomHttpHost) {}
  supports(strategy: ConnectionStrategy): boolean { return strategy.adapter === 'custom-http' || strategy.adapter === 'mcp-http'; }
  async connect(context: ConnectionAdapterContext): Promise<ConnectionAdapterResult> { const config = { ...(context.attempt.plan?.strategy.configuration || {}), ...(context.configuration || {}) }; const endpoint = typeof config.endpoint === 'string' ? config.endpoint : typeof config.url === 'string' ? config.url : ''; try { const url = new URL(endpoint); if (!['http:', 'https:'].includes(url.protocol)) throw new Error(); } catch { return { state: 'failed', error: { code: 'INVALID_ENDPOINT', message: 'A valid HTTP or HTTPS endpoint is required.', phase: 'planning' } }; } const probe = await this.host.probe(context, { ...config, endpoint }); if (!probe.ok) return { state: 'failed', error: { code: 'HTTP_PROBE_FAILED', message: probe.error || `Endpoint probe failed${probe.status ? ` with HTTP ${probe.status}` : ''}.`, retryable: true, phase: 'verifying', details: probe.details } }; const registered = await this.host.register(context, { ...config, endpoint }); return { state: 'verifying', configuration: { ...config, endpoint, ...registered }, connection: { configured: true, authenticated: Boolean(context.credentialRef) || config.authentication === 'none', authState: Boolean(context.credentialRef) || config.authentication === 'none' ? 'healthy' : 'none', registered: true, credentialRef: context.credentialRef } }; }
  async verify(context: ConnectionAdapterContext, connection: ConnectionRecord): Promise<ConnectionVerificationResult[]> { const probe = await this.host.probe(context, connection.configuration || {}); return [{ id: `${connection.id}:http`, check: 'http.reachability', passed: probe.ok, message: probe.error, details: { status: probe.status, ...probe.details }, verifiedAt: new Date().toISOString() }]; }
  async disconnect(context: ConnectionAdapterContext, connection: ConnectionRecord): Promise<void> { await this.host.unregister?.(context, connection); }
}
