import type { ConnectionAdapter, ConnectionAdapterContext, ConnectionAdapterResult, ConnectionRecord, ConnectionStrategy, ConnectionVerificationResult } from '../types.js';
export interface LocalResourceHost { validate(context: ConnectionAdapterContext, path: string, kind: 'file' | 'directory' | 'application'): Promise<{ ok: boolean; details?: Record<string, unknown>; error?: string }>; revoke?(context: ConnectionAdapterContext, connection: ConnectionRecord): Promise<void>; }
export class LocalResourceConnectionAdapter implements ConnectionAdapter {
  readonly id = 'local-resource'; readonly kind = 'local-resource'; readonly displayName = 'Local resource'; readonly priority = 60;
  constructor(private readonly host: LocalResourceHost) {}
  supports(strategy: ConnectionStrategy): boolean { return strategy.adapter === 'local-resource'; }
  async connect(context: ConnectionAdapterContext): Promise<ConnectionAdapterResult> { const config = { ...(context.attempt.plan?.strategy.configuration || {}), ...(context.configuration || {}) }; const path = typeof config.path === 'string' ? config.path : ''; const kind = config.resourceKind === 'file' || config.resourceKind === 'application' ? config.resourceKind : 'directory'; if (!path) return { state: 'awaiting_approval', userAction: { type: 'local-resource', label: `Choose a local resource for ${context.attempt.serviceName || context.attempt.serviceId}`, resourceKind: kind } }; const result = await this.host.validate(context, path, kind); if (!result.ok) return { state: 'failed', error: { code: 'LOCAL_RESOURCE_INVALID', message: result.error || 'The selected local resource is unavailable.', retryable: true, phase: 'verifying' } }; return { state: 'registering', configuration: { ...config, path, resourceKind: kind }, connection: { configured: true, authenticated: true, authState: 'healthy', configuration: { ...config, path, resourceKind: kind, validation: result.details } } }; }
  async continue(context: ConnectionAdapterContext, input: Record<string, unknown> = {}): Promise<ConnectionAdapterResult> { const path = typeof input.path === 'string' ? input.path : undefined; return this.connect({ ...context, configuration: { ...(context.configuration || {}), ...(path ? { path } : {}) } }); }
  async verify(context: ConnectionAdapterContext, connection: ConnectionRecord): Promise<ConnectionVerificationResult[]> { const config = connection.configuration || {}; const path = String(config.path || ''); const kind = config.resourceKind === 'file' || config.resourceKind === 'application' ? config.resourceKind : 'directory'; const result = await this.host.validate(context, path, kind); return [{ id: `${connection.id}:resource`, check: 'local-resource.access', passed: result.ok, message: result.error, details: result.details, verifiedAt: new Date().toISOString() }]; }
  async disconnect(context: ConnectionAdapterContext, connection: ConnectionRecord): Promise<void> { await this.host.revoke?.(context, connection); }
}
