import assert from 'node:assert/strict';
import { createMainChatStreamStore } from './main-chat-stream-store';

async function main() {
  const delivered: any[] = [];
  let runtimes: any[] = [];
  const store = createMainChatStreamStore({ broadcastWS: e => delivered.push(e), listLiveRuntimes: () => runtimes });
  const stream = store.beginMainChatStream(' replay ', 'runtime-1', 'lease-1');
  assert.equal(store.getMainChatStream('replay'), stream);
  assert.equal(store.appendMainChatStreamEvent('replay', 'stale', 'done', {}), null);
  const token = store.appendMainChatStreamEvent('replay', stream.streamId, 'token', { text: 'hello' })!;
  assert.equal(token.seq, 1);
  assert.equal(stream.events.length, 0, 'token is live-only');
  assert.equal(delivered.at(-1).event, 'token');
  const input = { state: 'running' };
  const progress = store.appendMainChatStreamEvent('replay', stream.streamId, 'progress_state', input)!;
  input.state = 'changed';
  assert.equal(progress.data.state, 'running', 'frame snapshots the payload');
  assert.equal(stream.progressState, progress.data);
  assert.deepEqual(stream.events.map(e => e.seq), [2], 'replay cursors preserve live-only sequence gaps');
  const cursor = progress.seq;
  store.appendMainChatStreamEvent('replay', stream.streamId, 'tool_call', { name: 'lookup_order', args: { id: 42 } });
  store.appendMainChatStreamEvent('replay', stream.streamId, 'tool_result', { name: 'lookup_order', result: 'shipped' });
  assert.deepEqual(stream.events.filter(e => e.seq > cursor).map(e => e.type), ['tool_call', 'tool_result']);
  assert.ok(store.buildDurableToolStreamTrace('replay')?.length, 'tool trace survives without vision frames');
  store.appendMainChatStreamEvent('replay', stream.streamId, 'custom_retained', {});
  const count = delivered.length;
  await new Promise(resolve => setTimeout(resolve, 950));
  assert.equal(delivered.length, count + 1, 'retained custom event emits throttled update');
  assert.equal(delivered.at(-1).lastSeq, stream.nextSeq - 1);
  runtimes = [{ id: 'remote', kind: 'main_chat', sessionId: 'replay', remoteHostPid: 123 }, { id: 'local', kind: 'main_chat', sessionId: 'replay', status: 'running' }];
  assert.deepEqual(store.findSessionMainChatRuntime('replay'), { id: 'local' });
  let aborted = '';
  stream.abortExecution = reason => { aborted = reason; };
  store.finishMainChatStreamAsOrphaned('replay', stream, 'runtime_missing');
  assert.equal(aborted, 'runtime_missing');
  assert.equal(stream.active, false);
  assert.equal(stream.events.at(-1)?.data.code, 'MAIN_CHAT_RUNTIME_OWNER_LOST');
  assert.equal(delivered.at(-1).active, false);
  const terminalSeq = stream.nextSeq;
  store.finishMainChatStreamAsOrphaned('replay', stream, 'again');
  assert.equal(stream.nextSeq, terminalSeq, 'orphan finish is idempotent');
  stream.completedAt = Date.now() - 46 * 60 * 1000;
  store.beginMainChatStream('next');
  assert.equal(store.getMainChatStream('replay'), null, 'completed streams expire after TTL');
  const capped = store.beginMainChatStream('cap');
  for (let i = 0; i < 12005; i++) store.appendMainChatStreamEvent('cap', capped.streamId, 'tool_call', { i });
  assert.equal(capped.events.length, 12000);
  assert.equal(capped.events[0].seq, 6);
  store.finishMainChatStream('cap', 'stale');
  assert.equal(capped.active, true);
  store.finishMainChatStream('cap', capped.streamId);
  const replacement = store.beginMainChatStream('cap');
  store.finishMainChatStream('cap', capped.streamId);
  assert.equal(replacement.active, true, 'old stream cannot finish replacement');
  console.log('main-chat-stream-store: PASS (replay gaps, trace, throttle, ownership, TTL, cap, replacement)');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
