function listFrom(body, key) {
  if (Array.isArray(body)) return body;
  return Array.isArray(body?.[key]) ? body[key] : [];
}
function scheduleRows(schedulesBody, brainBody) {
  const raw = listFrom(schedulesBody, 'schedules').length ? listFrom(schedulesBody, 'schedules') : listFrom(schedulesBody, 'jobs');
  const rows = raw.map((item) => ({ ...item, kind:'cron', id:String(item.id||item.scheduleId||''), name:String(item.name||item.title||'Schedule'), enabled:item.enabled!==false&&item.status!=='disabled', pattern:String(item.pattern||item.schedule||item.cron||'') }));
  const brain=brainBody?.brain||brainBody||{}; const thoughtEnabled=brain.thoughtEnabled??brain.thought?.enabled; const dreamEnabled=brain.dreamEnabled??brain.dream?.enabled;
  if(thoughtEnabled!==undefined||brain.thought) rows.unshift({id:'brain-thought',kind:'brain',brainType:'thought',name:'Brain Thought',enabled:thoughtEnabled!==false,pattern:String(brain.thought?.schedule||'Every 6 hours'),raw:brain.thought||{}});
  if(dreamEnabled!==undefined||brain.dream) rows.unshift({id:'brain-dream',kind:'brain',brainType:'dream',name:'Brain Dream',enabled:dreamEnabled!==false,pattern:String(brain.dream?.schedule||'Nightly'),raw:brain.dream||{}});
  return rows;
}
export class FeatureClient {
  constructor(gatewayManager){this.gateways=gatewayManager;} get api(){return this.gateways.active;}
  tasks(){return this.api.request('/api/bg-tasks?mobile=1').then(r=>listFrom(r,'tasks'));} task(id){return this.api.request(`/api/bg-tasks/${encodeURIComponent(id)}`);} taskEvidence(id){return this.api.request(`/api/bg-tasks/${encodeURIComponent(id)}/evidence`).then(r=>listFrom(r,'entries')).catch(()=>[]);} taskMessage(id,message){return this.api.request(`/api/bg-tasks/${encodeURIComponent(id)}/message`,{method:'POST',body:JSON.stringify({message})});} taskAction(id,action){if(action==='delete')return this.api.request(`/api/bg-tasks/${encodeURIComponent(id)}`,{method:'DELETE'});return this.api.request(`/api/bg-tasks/${encodeURIComponent(id)}/${encodeURIComponent(action)}`,{method:'POST',body:'{}'});}
  async schedules(){const[schedules,brain]=await Promise.all([this.api.request('/api/schedules').catch(()=>null),this.api.request('/api/brain/status').catch(()=>null)]);return scheduleRows(schedules,brain);} createSchedule(fields){return this.api.request('/api/schedules',{method:'POST',body:JSON.stringify({...fields,confirm:true})});} runSchedule(item){if(item.kind==='brain')return this.api.request('/api/brain/run',{method:'POST',body:JSON.stringify({type:item.brainType})});return this.api.request(`/api/schedules/${encodeURIComponent(item.id)}/run`,{method:'POST',body:'{}'});} toggleSchedule(item,enabled){if(item.kind==='brain'){const key=item.brainType==='thought'?'thoughtEnabled':'dreamEnabled';return this.api.request('/api/brain/config',{method:'PATCH',body:JSON.stringify({[key]:!!enabled})});}return this.api.request(`/api/schedules/${encodeURIComponent(item.id)}`,{method:'PUT',body:JSON.stringify({enabled:!!enabled})});} updateSchedule(item,fields){return this.api.request(`/api/schedules/${encodeURIComponent(item.id)}`,{method:'PUT',body:JSON.stringify(fields||{})});} deleteSchedule(item){return this.api.request(`/api/schedules/${encodeURIComponent(item.id)}`,{method:'DELETE',body:JSON.stringify({confirm:true})});}
  teams(){return this.api.request('/api/teams').then(r=>listFrom(r,'teams'));} teamRuns(id,limit=30){return this.api.request(`/api/teams/${encodeURIComponent(id)}/runs?limit=${limit}`).catch(()=>({runs:[]}));} teamRoom(id){return this.api.request(`/api/teams/${encodeURIComponent(id)}/room-state`).catch(()=>null);} teamWorkspace(id){return this.api.request(`/api/teams/${encodeURIComponent(id)}/workspace`).catch(()=>({files:[]}));} teamWorkspaceFile(id,relpath){const filename=encodeURIComponent(String(relpath||'').split('/').pop()||'file');return this.api.request(`/api/teams/${encodeURIComponent(id)}/workspace/${filename}?relpath=${encodeURIComponent(relpath)}`);} teamAction(id,action){if(action==='delete')return this.api.request(`/api/teams/${encodeURIComponent(id)}`,{method:'DELETE'});const suffix=action==='review'?'manager/trigger':action;return this.api.request(`/api/teams/${encodeURIComponent(id)}/${suffix}`,{method:'POST',body:'{}'});} saveTeamContext(id,title,body){return this.api.request(`/api/teams/${encodeURIComponent(id)}/context-references`,{method:'POST',body:JSON.stringify({title,body})});} teamChat(id,limit=80){return this.api.request(`/api/teams/${encodeURIComponent(id)}/chat?limit=${limit}`).then(r=>listFrom(r,'messages'));} streamTeamChat(id,message,options={}){return this.api.streamRequest(`/api/teams/${encodeURIComponent(id)}/chat/stream`,{method:'POST',body:{message},...options});}
  agents(){return this.api.request('/api/agents').then(r=>listFrom(r,'agents'));} async agent(id){return(await this.agents()).find(row=>String(row.id)===String(id))||null;} agentText(id,name){return this.api.request(`/api/agents/${encodeURIComponent(id)}/${name}`).catch(()=>({content:'',exists:false}));} agentHeartbeat(id){return Promise.all([this.api.request(`/api/heartbeat/agents/${encodeURIComponent(id)}`).catch(()=>null),this.agentText(id,'heartbeat-md')]).then(([status,file])=>({status,file}));} tickAgent(id){return this.api.request(`/api/heartbeat/agents/${encodeURIComponent(id)}/tick`,{method:'POST',body:'{}'});} agentRuns(id,limit=30){return this.api.request(`/api/agents/${encodeURIComponent(id)}/runs?limit=${limit}`).then(r=>listFrom(r,'runs')).catch(()=>[]);} agentContextRefs(id){return this.api.request(`/api/agents/${encodeURIComponent(id)}/context-refs`).then(r=>listFrom(r,'refs')).catch(()=>[]);} spawnAgent(id,task,timeoutMs=180000){return this.api.request(`/api/agents/${encodeURIComponent(id)}/spawn`,{method:'POST',body:JSON.stringify({task,timeoutMs}),timeoutMs:timeoutMs+10000});} agentChat(id,limit=100){return this.api.request(`/api/agents/${encodeURIComponent(id)}/chat?limit=${limit}`).then(r=>listFrom(r,'messages')).catch(()=>[]);} streamAgentChat(id,message,options={}){return this.api.streamRequest(`/api/agents/${encodeURIComponent(id)}/chat/stream`,{method:'POST',body:{message},...options});}
  proposals(status='pending'){return this.api.request(`/api/proposals?status=${encodeURIComponent(status)}`).then(r=>listFrom(r,'proposals'));} proposal(id){return this.api.request(`/api/proposals/${encodeURIComponent(id)}`);} proposalAction(id,action){return this.api.request(`/api/proposals/${encodeURIComponent(id)}/${action}`,{method:'POST',body:'{}'});}
  hubOverview(){return Promise.all([this.api.request('/api/hub/models/overview?range=all').catch(()=>null),this.api.request('/api/hub/tools/overview?range=30d').catch(()=>null),this.api.request('/api/hub/goals').catch(()=>null)]).then(([models,tools,goals])=>({models,tools,goals:listFrom(goals,'goals')}));} audit(limit=80){return this.api.request(`/api/audit-log?limit=${limit}&offset=0&nonMainOnly=1`).catch(()=>({runs:[]}));} memory(){return this.api.request('/api/memory/graph').catch(()=>({nodes:[],edges:[]}));}
  voiceStatus(){return Promise.all([this.api.request('/api/voice/status').catch(()=>null),this.api.request('/api/realtime/status').catch(()=>null)]).then(([voice,realtime])=>({voice,realtime}));} transcribe(payload){return this.api.request('/api/voice/transcribe',{method:'POST',body:JSON.stringify(payload),timeoutMs:120000});} voiceStt(payload){return this.api.request('/api/voice/stt',{method:'POST',body:JSON.stringify(payload),timeoutMs:120000});} voiceTts(payload){return this.api.request('/api/voice/tts',{method:'POST',body:JSON.stringify(payload),timeoutMs:120000});}
  heartbeat(){return this.api.request('/api/settings/heartbeat').catch(()=>null);} saveHeartbeat(fields){return this.api.request('/api/settings/heartbeat',{method:'POST',body:JSON.stringify(fields||{})});} status(){return this.api.request('/api/status').catch(()=>null);}
}
